### ISSUE TITLE
[BUG] unable to synchronize repository

### ISSUE THREAD

**Issue by btimofeev** [zeapo/Android-Password-Store#1092]
**Describe the bug**
Synchronizing the repository throws an error: "An error occurred during a Git operation. cannot open additional channels". 
However, the separate "push to remote" and "pull from remote" commands work well.

**To Reproduce**
1. Open menu
2. Click on 'Synchronize repository'
3. Enter SSH passphrase
4. See error dialog

**Device information (please complete the following information):**
 - Device: Xiaomi Mi A3
 - OS: Android 10.0
 - App version: 1.11.3

**Comment by fmeum** [comment]
@btimofeev Could you tell us where your Git remote is hosted?

@msfjarvis I fear this is due https://community.atlassian.com/t5/Bitbucket-questions/Can-t-repo-sync-anymore/qaq-p/354231 or a similar issue where the remote does not support multiplexing. I didn't know there are remotes that do not allow this when I created https://github.com/android-password-store/Android-Password-Store/pull/1012.

Our options include special casing this error message and falling back to non-multiplexed SSH connections automatically or introducing a global configuration that allows to do this. In fact, it would probably be much easier to just run a pull followed by a push instead of meddling with `SshjSessionFactory` internals.

**Comment by btimofeev** [comment]
I use bitbucket.

**Comment by msfjarvis** [comment]
> I use bitbucket.

And...fuck me.


> @msfjarvis I fear this is due [community.atlassian.com/t5/Bitbucket-questions/Can-t-repo-sync-anymore/qaq-p/354231](https://community.atlassian.com/t5/Bitbucket-questions/Can-t-repo-sync-anymore/qaq-p/354231) or a similar issue where the remote does not support multiplexing. I didn't know there are remotes that do not allow this when I created #1012.

Yeah that's the issue, I've seen it a couple years ago on an unrelated problem involving the same thing.

> Our options include special casing this error message and falling back to non-multiplexed SSH connections automatically or introducing a global configuration that allows to do this. In fact, it would probably be much easier to just run a pull followed by a push instead of meddling with `SshjSessionFactory` internals.

I'm trying to eventually reduce the number of configuration knobs we expose to users so I'm certainly not a fan of adding another one. We might have to settle with special-casing the error.

**Comment by fmeum** [comment]
In that case, in order to keep things simple, I would recommend the following:

1. Introduce a preference that, if set to true, makes Sync behave like a separate pull and push.
2. When this error message is encountered, let the user know something understood went wrong and instruct them to try again. Enable the preference.
3. Clear the preference when the repository url changes.

This way we don't have to launch git operations from an error handler.

**Comment by msfjarvis** [comment]
> In that case, in order to keep things simple, I would recommend the following:
> 
> 1. Introduce a preference that, if set to true, makes Sync behave like a separate pull and push.
> 2. When this error message is encountered, let the user know something understood went wrong and instruct them to try again. Enable the preference.
> 3. Clear the preference when the repository url changes.
> 
> This way we don't have to launch git operations from an error handler.

Sounds good to me.
