### ISSUE TITLE
OpenKeychain SSH Authentication Mode broken

### ISSUE THREAD

**Issue by TinfoilSubmarine** [zeapo/Android-Password-Store#1164]
When using OpenKeychain authentication mode for synchronizing my repository, I get the following error:

![index](https://user-images.githubusercontent.com/19600707/96934686-a5890a80-1490-11eb-8cd8-f8e98a45e738.jpg)
Transcription: 
**An error occurred during a Git operation**
LifecycleOwner com.zeapo.pwdstore.git.GitServerConfigActivity@f578da1 is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.

Confirmed with two separate servers (self-hosted Gitea and private Github repo). Tested same two servers/repos with regular SSH keys generated from the app, and these both worked normally.

**Comment by msfjarvis** [comment]
Hm this is a tough one. The error originates [here](https://github.com/android-password-store/Android-Password-Store/blob/4a9151870d8e5196248b2abc09df8fbb1593c265/app/src/main/java/com/zeapo/pwdstore/git/sshj/OpenKeychainKeyProvider.kt#L63), because we create the key provider right before using it. Unfortunately, this is in violation of the lifecycle expectations mandated by AndroidX which we did fix in cf03c554785e but overlooked this one case because of the indirection masking it. I'm not sure how to fix this yet. @FabianHenneke any thoughts?

**Comment by fmeum** [comment]
Whelp, I thought that this possibility of late initialization was a feature of the new API... We may need a subclass of `FragmentActivity` and override `onActivityResult`, as in the good old days. I don't currently see a better encapsulated way of doing this as we do need to pass the continuation into the result handler.

**Comment by msfjarvis** [comment]
> Whelp, I thought that this possibility of late initialization was a feature of the new API... We may need a subclass of `FragmentActivity` and override `onActivityResult`, as in the good old days. I don't currently see a better encapsulated way of doing this as we do need to pass the continuation into the result handler.

It was, briefly. Then lifecycle checks were implemented exhaustively. I'm not making much progress at day job stuff so I'll give this a shot now before I head for lunch.
