### ISSUE TITLE
Option to solve detached HEAD git sync exception

### ISSUE THREAD

**Issue by githlp** [zeapo/Android-Password-Store#1231]
**Is your feature request related to a problem? Please describe.**
I had the following exception with the F-Droid v1.13.1:

Internal exeception occured
HEAD is detached

No idea how i came to the detached head within the application, the other two (computer) clients had no problem syncing.

**Describe the solution you'd like**
Option or possibility to check what happened before that led to detach state (on non rooted phone)

**Describe alternatives you've considered**
I was not able to solve it (even with Hard reset) and therefor finally removed the local repo so i could clone again from remote.

**Additional context**

**Comment by msfjarvis** [comment]
If you're ever on a detached HEAD state then the 'Abort rebase and push new branch' button should become available in the 'Local Git config & utilities' settings menu which will let you push your detached state as a new branch that you can use to resolve the rebase error which caused this in the first place. Do you not get that option on your device?

**Comment by githlp** [comment]
Yes, i used that and checked out to conflicting-master-1607.... 
but
1. how do you then further examine the problem that the HEADs pointer lost the corresponding branch ?
2. how do you examine the problem when you have only your mobile (at home i usually do not pull/push on mobile, since i work on computer/laptop)

Thanks in advance, besides this problem the app is really great!

**Comment by msfjarvis** [comment]
> Yes, i used that and checked out to conflicting-master-1607....
> but
> 
> 1. how do you then further examine the problem that the HEADs pointer lost the corresponding branch ?

It's caused by a rebase failure when the commit history of the repository diverges from what is available on the remote.

> 2. how do you examine the problem when you have only your mobile (at home i usually do not pull/push on mobile, since i work on computer/laptop)

You cannot, since it requires an interactive Git tool that APS is not. Your best bet is to install [Termux](https://play.google.com/store/apps/details?id=com.termux), clone your repository inside it (use `pkg update && pkg install git` to install git) and then resolve the failure and push it back to the remote. Then the hard reset option in APS should be able to restore your repo to match the remote again.

**Comment by githlp** [comment]
Thanks, i will try that.

I appreciate your work and will support APS soon.
