### ISSUE TITLE
[BUG] Galician (gl) language not inlcuded on v1.13.1

### ISSUE THREAD

**Issue by xmgz** [zeapo/Android-Password-Store#1254]
**Bug description**
* APS (android password store) IS NOT following default UI setting on an android device.
* I went to transifex to check if it was translated (it is, because I had translated since legacy versions < v1)
* I came to github and galician language **is not included in the code** https://github.com/android-password-store/Android-Password-Store/tree/develop/app/src/main/res son app can not use it.

**To Reproduce**
1. android OS with galician (gl) language set as default
2. install APS
3. open APS

**Expected behavior**
UI using _gl_ locale, as any other app in the system.

**Device information (please complete the following information):**
 - Device: BQ x2
 - OS: LineageOS Android 9
 - App version 1.13.1 (latest from f-droid)

**Comment**

please add galician language to the next release. Thank you.

**Comment by msfjarvis** [comment]
We now do translation via [Crowdin](https://crowdin.com/project/android-password-store), where Galician appeared to already be translated so I've imported it in #1256. Unfortunately we've suspended new releases for a while so you will need to switch to the [Snapshot builds](https://android-password-store.github.io/docs/users/release-channels) in order to gain access to the development builds.

**Comment by msfjarvis** [comment]
Galician will be available in the v1.13.2 release that is going out right now and will become available in a few hours on the Google Play Store.
