### ISSUE TITLE
[BUG] Existing files checking issues when renaming a file

### ISSUE THREAD

**Issue by Jangberry** [zeapo/Android-Password-Store#1285]
**Describe the bug**
When renaming a file, the app doesn't check for existing files as it does when creating a file, therefore may delete a password

**To Reproduce**
1. Create two new password with different names
2. Rename one of them like the other
3. There is only one password

**Expected behavior**
The app should send a toast notification as it does when we try to create a password with an existing name

**Screenshots**
![initially](https://i.imgur.com/5mylviX.png)

![when I rename test2 to test](https://i.imgur.com/tYO71Z8.png)

**Device information (please complete the following information):**
 - Device: Cubot Power
 - OS: Stock ROM Android 8 AOSP
 - App version 1.13.2 FDroid

**Comment by msfjarvis** [comment]
This is a bug stemming from our re-use of the password creation screen for password editing. We have a check for the file already existing as you have observed that creation does fail, but that check has an 'escape hatch' where its bypassed when editing because it is expected that the target file will exist. Maybe it is finally time to split the two...

**Comment by msfjarvis** [comment]
I've filed #1286 to fix this with a bandaid for now, and will follow up with a larger refactor soon. Thanks for your detailed report.
