### ISSUE TITLE
[BUG] BouncyCastle is required to read a key of type ecdsa-sha2-nistp521

### ISSUE THREAD

**Issue by grobx** [zeapo/Android-Password-Store#1294]
**Describe the bug**
I can't clone my repository because the key used is of type ecdsa-sha2-nistp521 and it seems it's not supported. Openkeychain works fine, I tried to decrypt a message and it works.

**To Reproduce**
1. Open Password Store
2. Click on 'Let's go'
3. Click on 'Clone Remote Repo'
4. Enter repository URL and branch
5. Select Openkeychain as authentication method
6. Click 'Clone'
7. Select the key from Openkeychain
8. Error: BouncyCastle is required to read a key of type ecdsa-sha2-nistp521

**Expected behavior**
I expected the repository to be cloned

**Device information (please complete the following information):**
 - Device: Xiaomi Redmi Note 8 Pro
 - OS: Lineage OS 17.1 unofficial ROM
 - App version 1.13.2

**Comment by msfjarvis** [comment]
This is curious, because we do [install Bouncycastle](https://github.com/android-password-store/Android-Password-Store/blob/4694c5ac8575a7e85e6b950eaed99049719b6151/app/src/main/java/dev/msfjarvis/aps/util/git/sshj/SshjConfig.kt#L35-L56) as a SecurityProvider. Logcat confirms that BC is loaded

```
JCE providers: AndroidNSSP (1.0), AndroidOpenSSL (1.0), CertPathProvider (1.0), AndroidKeyStoreBCWorkaround (1.0), BC (1.67), HarmonyJSSE (1.0), AndroidKeyStore (1.0)
```

The exception thrown is

```
net.schmizz.sshj.common.SSHRuntimeException: BouncyCastle is required to read a key of type ecdsa-sha2-nistp521
      at net.schmizz.sshj.common.Buffer.readPublicKey(Buffer.java:473)
```

Tracking the control flow, the exception is thrown [here](https://github.com/hierynomus/sshj/blob/b8d58389cf21819f162f9bcecee24a74a3da782e/src/main/java/net/schmizz/sshj/common/ECDSAVariationsAdapter.java#L61) because of the return value from [SecurityUtils#isBouncyCastleRegistered](https://github.com/hierynomus/sshj/blob/b8d58389cf21819f162f9bcecee24a74a3da782e/src/main/java/net/schmizz/sshj/common/SecurityUtils.java#L250-L260), which is in disagreement with our own logging.

That's where my understanding fizzles out, so Fabian will probably have to step in to fill the gaps in my knowledge.

Here's an [OpenKeychain generated PGP key](https://github.com/android-password-store/Android-Password-Store/files/5913366/key.zip) that reliably reproduces the issue, just in case.

**Comment by fmeum** [comment]
> Tracking the control flow, the exception is thrown [here](https://github.com/hierynomus/sshj/blob/b8d58389cf21819f162f9bcecee24a74a3da782e/src/main/java/net/schmizz/sshj/common/ECDSAVariationsAdapter.java#L61) because of the return value from [SecurityUtils#isBouncyCastleRegistered](https://github.com/hierynomus/sshj/blob/b8d58389cf21819f162f9bcecee24a74a3da782e/src/main/java/net/schmizz/sshj/common/SecurityUtils.java#L250-L260), which is in disagreement with our own logging.

[My patch](https://github.com/hierynomus/sshj/commit/2edaf07e71ded291b81d87ac8ae1062c6692027e) for `SecurityUtils#isBouncyCastleRegistered` has not been included in a release yet. We should be eagerly awaiting 0.31.0 not just because of that fix but also because of the AES-GCM support it brings.

**Comment by msfjarvis** [comment]
@fmeum I e-mailed Jeroen yesterday and he's been kind enough to do the [0.31.0](https://github.com/hierynomus/sshj/commit/1d8eaa7ce29c9d08173d1ccf5b8dcf6b3871e356) release. If this just needs a version bump then I can put up a PR otherwise I'll let you handle it.

**Comment by msfjarvis** [comment]
I tried the upgrade locally, and it seems there's an internal failure in SSHJ which probably means we need to change things on our end

```
Dying because - dev.msfjarvis.aps.util.git.sshj.OpenKeychainKeyProvider$makePrivateKey$1 cannot be cast to java.security.interfaces.ECKey
```

When the operation finally fails as a result, there's also a suppressed exception from AndroidX Lifecycle thrown in `OpenKeychainKeyProvider`.

```
java.lang.IllegalStateException: Method removeObserver must be called on the main thread
```

I'll let you handle this and go fight Flutter at work instead :smile:

**Comment by grobx** [comment]
Was this fixed in 1.13.3? I've upgraded it form play store but the problem is still here, maybe I'm doing something wrong.

**Comment by msfjarvis** [comment]
It is not included in 1.13.3, but I need to make another patch release this weekend and I will make sure to include the fix for this.

**Comment by grobx** [comment]
Thank you @msfjarvis

**Comment by msfjarvis** [comment]
@roberti42 #1314 has been included in the [v1.13.4](https://github.com/android-password-store/Android-Password-Store/releases/tag/v1.13.4) release and should become available on the Play Store over the next few hours and on F-Droid sometime next week. Thanks for bringing it to my attention.

**Comment by grobx** [comment]
Now I can clone the repository, but when I try to decrypt a password file it tells me "Error: Invalid KEK!". Do I have to open a different issue?

**Comment by msfjarvis** [comment]
> Now I can clone the repository, but when I try to decrypt a password file it tells me "Error: Invalid KEK!". Do I have to open a different issue?

Yes please.
