### ISSUE TITLE
[FEATURE] Import from Google

### ISSUE THREAD

**Issue by Chrisnetika** [zeapo/Android-Password-Store#1315]
**Is your feature request related to a problem? Please describe.**
-No

**Describe the solution you'd like**
-To be able when creating a repo to import passwords already in Google account that been saved from Chrome

**Describe alternatives you've considered**
-Somehow exporting passwords manually and converting them in some way that can work in Password Store

**Additional context**
-Doesn't seem like this has been requested before tho it seems like it can be useful unless i'm missing something let me know!

**Comment by msfjarvis** [comment]
We're not going to be building any import tools into APS. Please use [pass-import](https://github.com/roddhjav/pass-import) on a Linux desktop to import your passwords from Google Chrome.

**Comment by Chrisnetika** [comment]
what your suggesting is for command line version of password store, i'm trying import into the android app, what you pointed me to does not make sense zzz

**Comment by msfjarvis** [comment]
> what your suggesting is for command line version of password store, i'm trying import into the android app, what you pointed me to does not make sense zzz

It is what it is. We will not add any import mechanism into the app because a) it'd be an extremely large maintenance burden, b) it's going to be extremely slow, and c) pass-import is far superior at doing this and will always be better than anything we add to the app.

If you cannot use pass-import then I'm sorry but I have nothing else to offer you.
