### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by ghost** [zeapo/Android-Password-Store#1337]
If you suspect that this message may have been intercepted or amended, please call the sender.

**Comment by msfjarvis** [comment]
We have password authentication as a fallback so if you're being prompted for it, that means SSH key authentication failed. Please double check your server configuration.

**Comment by braderhart** [comment]
I have password authentication disabled. I'm using a setup similar to this:

https://wiki.archlinux.org/index.php/OpenSSH#PAM_setup

It is working fine if I remove:

```
AuthenticationMethods publickey,keyboard-interactive:pam
```

Additionally, I have it setup to bypass `pam_google_authenticator.so` if I'm on my local network and it works fine using Git, only asking for the SSH key password like expected:

https://wiki.archlinux.org/index.php/Google_Authenticator#Request_OTP_only_when_connecting_from_outside_your_local_network

It is only with Android Password Store where I encounter the issue. I'm guessing it has something to do with the Git/SSH implementation being used in the app that prevents this from working. I'm still trying to figure out how to debug the PAM modules, since I don't even get logs otherwise about why it is failing. I believe it is still using the keyboard-interactive:pam method and is failing here, most likely because it isn't implemented:

```
auth [success=1 default=ignore] pam_access.so accessfile=/etc/security/access-local.conf
```

**Comment by msfjarvis** [comment]
Hm thanks for the info, I'll need to test a couple things. We don't support OTP entry for SSH right now but it's come up before so maybe we'll consider it sometime soon.

**Comment by msfjarvis** [comment]
Took a while to actually test this, but from what I can tell PAM always causes this to break but I'm rather unsure why OpenSSH also sends the `USERAUTH_FAILURE` packet with `AuthenticationMethods publickey,keyboard-interactive` despite the key not actually changing between that and `AuthenticationMethods publickey`. @fmeum?

**Comment by fmeum** [comment]
> Took a while to actually test this, but from what I can tell PAM always causes this to break but I'm rather unsure why OpenSSH also sends the `USERAUTH_FAILURE` packet with `AuthenticationMethods publickey,keyboard-interactive` despite the key not actually changing between that and `AuthenticationMethods publickey`. @fmeum?

Sorry, I have never used authentication methods other than `publickey`. I'm afraid I can't make sense of this.

**Comment by msfjarvis** [comment]
Closing as part of [issue tracker cleanup](https://github.com/android-password-store/Android-Password-Store/discussions/1836).
