### ISSUE TITLE
[FEATURE] Support unencrypted `git://` protocol

### ISSUE THREAD

**Issue by TobTobXX** [zeapo/Android-Password-Store#1454]
**Is your feature request related to a problem? Please describe.**
My pass store is in a git repository that is accessible via the git:// protocol. Yes, I know this doesn't allow for authentication, but that's fine, because (a) the store repo is encrypted and (b) in my case it is only accessible within a VPN.

**Describe the solution you'd like**
Additionally to supporting the https:// and ssh:// protocol, the git:// protocol could be supported too. That should be even easier, since there is no authentication at all.

**Describe alternatives you've considered**
Granted, my git server offers ssh access, but I don't want my key to be on my phone just like that.

**Additional context**
Not sure though if JGit supports this. I tried googling, but it this is very hard to search for and I'm not familiar with JGit.

**Comment by msfjarvis** [comment]
The choice to disallow `git://` is intentional and not going to change. FWIW, an SSH key is significantly more secure on a modern Android phone than the average Linux desktop, so generating one within Password Store and using it for authentication is going to be my suggestion regardless of your network sandbox.
