### ISSUE TITLE
Please do not use bare external directory as a place to store the database

### ISSUE THREAD

**Issue by amtlib-dot-dll** [zeapo/Android-Password-Store#148]
I just come to use this application. The default location for external database is `/sdcard`.

And I want a fresh restart, so I pressed "Delete Repository", and all of my data was lost. The `/sdcard` directory is treated by the application as the database to purge.

There shall be many choices to circumvent this.

For me I should backup my photos and documents to the hard drive regularly, because cloud synchronization costs too much here.

HOWEVER, FOR THE DEVELOPERS OF THIS APPLICATION, I SUGGEST THAT THE DATABASE SHOULD BE STORED IN A SPECIFIC PLACE, EITHER INSIDE `/data/data/com.zeapo.pwdstore` OR INSIDE `/sdcard/Android/data/com.zeapo.pwdstore`, AND THERE SHOULD BE A METHOD TO BARELY EXPORT THE DATABASE OUT BECAUSE SOME USERS, LIKE ME, HAVE NO GIT REPOSITORY TO SYNCHRONIZE. YOU MAY USE THE STORAGE ACCESS FRAMEWORK WHICH IS SUGGESTED BY GOOGLE. THANK YOU VERY MUCH.

Sorry for my bad temper, and if you feel hard to read the capitalized text you may use some tools to convert it. Thank you again and I won't use this application any more until any change.

**Comment by wongma7** [comment]
Sorry this happened to you. #129 experienced the same thing. I have made it so that by default the app will create and choose a new empty folder, and when it prompts you to delete the folder it will show you what folder it is trying to delete. 

The app makes the dangerous/wrong assumption that the user will choose some empty folder, even though the default choice is certainly not empty. Choosing 'Internal' at setup will store the data in /data/data/com.zeapo.pwdstore, and the purpose of 'External' is to give users full control over where to store the data. Since the app assumes that the directory it is deleting contains only data that was put there by the app itself, it should accept nothing but an empty directory at setup...I will add this check soon.

**Comment by amtlib-dot-dll** [comment]
Thank you for reply. I think that to store the database itself on the external storage is not a good idea because that malware, or something else, will delete the database on purpose, which is also a lost, although other apps have no means to retrieve data from it.

The data won't leak. They'll lose.

My preferred way is to store the database on the internal storage and to allow users to export them out when needed.

The problem, actually for me now, is that I cannot export the database out because I have no `git` server and GitHub is not stable without VPN, which is literally expensive. Thank you very much.

**Comment by wongma7** [comment]
Yes, that's a good idea to have an export feature. Otherwise users would need a rooted device + file explorer to get to /data/data and that's of course not fair. I can't make a decision on removing the 'external' option completely though. For now I will just try to make it impossible for problems to occur.

**Comment by amtlib-dot-dll** [comment]
Thank you very much! It will be very nice of you if modern Android frameworks like Content Provider and Storage Access Framework are used.

**Comment by zeapo** [comment]
Sorry for that. The passwords can (and by default are) stored in the data folder of the application. Using the external storage is up to the user. We will prevent the user from using the sdcard root directory as a store to avoid any issue. 

Storage Access Framework is not supported prior to kitkat. And we have many 4.1 and 4.3 users.

For the Content Provider, I honestly didn't know this feature and that seems great. I will take a look and open an issue for someone to implement it soon, or I will do it later.

**Comment by zeapo** [comment]
5b3cc540e413395dc4771d810058fcd467efab4c shows more information to the user and warns the user if (s)he sets the sdcard as a store. 
5d6d349e6242f49aa5bf71aef96da8dfe92a65db warns the user if he is using a non-empty directory.

**Comment by amtlib-dot-dll** [comment]
Thank you very much! I noticed that the original `pass` utility uses `git` as the method to backup, and the storage is readable to the user, just like the external storage on Android. Therefore this application is just a port of that Unix utility. Thanks anyway!
