### ISSUE TITLE
[BUG] Decrypted password screen does not render all extra content pairs

### ISSUE THREAD

**Issue by plant7403** [zeapo/Android-Password-Store#1525]
Hi, i use APS not only as a password manager
I use it as a note app
But when i started to do:
Field1: ,Field2:...
I noticed that i actually can't put more than 9 fields there 😿
I know, it's kinda strange request to have more than 9 fields in a password manager 😅
But is it really neccesary to keep it so? 😇
Thank you😁

**Comment by plant7403** [comment]
Ah, also, i know about the issue template
I tried many times, but it was giving me only one option 🤨 and it was not issue and not feature request

**Comment by msfjarvis** [comment]
You're using an outdated GitHub client if you do not see the options. For the future, use [this](https://github.com/android-password-store/Android-Password-Store/issues/new/choose) link to create issues on the web.

Regarding the topic of this specific issue, there is no limit enforced by us on how many line items you can put inside your password entry, so I have no clue what this issue is about.

**Comment by plant7403** [comment]
@msfjarvis oh, i'm using octodroid 😅 it gives me only [RFC] option

About the issue, something very strange is going on there
After 9 fields i need to add 1 field more to see field 10
So i add field 10, and add 1 more to see field 10
And at the same time, field 11 stays hidden

Ah, and also, i forgot to mention the version, it's 2.0.0 from snapshots

**Comment by msfjarvis** [comment]
Reproduced, working on a fix.

**Comment by msfjarvis** [comment]
The parsing code is correct, UI will be triaged by Aditya.

**Comment by msfjarvis** [comment]
GitHub messed up, the issue isn't fixed.
