### ISSUE TITLE
External repository broken on Marshmallow

### ISSUE THREAD

**Issue by djl** [zeapo/Android-Password-Store#155]
I just moved to a new phone (running Marshmallow) and noticed an issue when setting up the app for the first time. Basically, the UI for choosing the external repository doesn't display any directories.

Steps to reproduce:

1. Open app settings
2. Enable "External repository"
3. Tap "Select external repository"
4. Notice the file/directory chooser is blank

This seems to be a permission issue. If I manually enable the "Storage" permission for the app (`Settings -> Apps`) the issue is fixed.

Does the app need to explicitly request this permission now?

**Comment by rndstr** [comment]
Yes, it is supposed to: http://developer.android.com/training/permissions/requesting.html

**Comment by garyschulte** [comment]
How does this help?  There is no dialog to give perms?

**Comment by bgaluszka** [comment]
To add to that, I can't import ssh key (Nexus 5X). I can choose it but then I get permission denied. Turning storage permission on helped.

**Comment by wongma7** [comment]
Right, there's a bunch of stuff the app has to do to comply with the new permissions system. Will try to get this done next week!

@garyschulte In the latest version's setup, it was made clearer that the password are either stored 'hidden' i.e. in the app's private folder or on the 'sdcard'. I guess 'external repository' should also be renamed accordingly to...'store on sdcard' or something.

**Comment by garyschulte** [comment]
@wongma7 - I noticed that when I built the latest.  Much clearer :)

**Comment by wongma7** [comment]
Okay, when the app changed to a different directory chooser library in the latest version, that actually fixed this issue because the library requests it for the app before letting you pick a folder.

Also, interestingly I can't replicate the ssh key import error, I am able to browse the whole sdcard through the 'import ssh key' ui and pick one even though I didn't give the app permission...

BTW there are many cases where the app will crash if the user for some reason revokes permission during runtime or any time after they granted it. I am working on preventing crashes at startup but I don't think it's worth it to handle all of the other cases.
