### ISSUE TITLE
OTP: Show for how long the code is still valid for

### ISSUE THREAD

**Issue by s1shed** [zeapo/Android-Password-Store#1550]
It would be a nice feature to show for how long the TOTP code will still be valid.

With a similar app on iOS it looks like this:

![image](https://user-images.githubusercontent.com/8793762/143070062-d42c21a7-6549-4f28-8ae3-2ee6952fc7a1.png)

**Comment by msfjarvis** [comment]
I'm not working on this, leaving implementation notes for anyone else who wishes to pick it up:

- The remaining valid time for a TOTP is calculated internally in `dev.msfjarvis.aps.data.passfile.PasswordEntry`.
- One way to resolve this issue is to convert the `totp` `StateFlow<String>` into a `StateFlow<Pair<String, Int>>` to return the TOTP and remaining time in seconds to the UI layer, and the UI can handle counting down.
