### ISSUE TITLE
For ssh uses default port instead of custom

### ISSUE THREAD

**Issue by bgaluszka** [zeapo/Android-Password-Store#158]
When I configure repository to use ssh protocol on a custom port app still tries to connect to default 22 (checked with tcpdump on server side).

**Comment by bgaluszka** [comment]
Error message is

```
Internal exception occurred

Message from jgit:

username@example.com:1022/directory/subdirectory: failed to connect to example.com/192.0.2.1 (port 22): connect failed: ETIMEDOUT (Connection timed out)
```

**Comment by wongma7** [comment]
Try this: "add the protocol ssh:// in the 'resulting URL' field before the username." https://github.com/zeapo/Android-Password-Store/issues/94#issuecomment-154488960

**Comment by bgaluszka** [comment]
I've tried that and got "Auth failed". Password-Store connected to proper port but on a server side I got "sshd[31559]: error: RSA_public_decrypt failed: error:0407006A:lib(4):func(112):reason(106)". I've checked multiple times and key/pass are valid, so not sure if that's application or me :)

**Comment by wongma7** [comment]
Can you tell me about the key properties i.e. length, format, encryption type? Weird error. thanks.

**Comment by bgaluszka** [comment]
From `ssh-keygen -l -f ssh.pub`:

```
2048 SHA256:mYHWl/nOHYZUAg9QY0PxpmFVbzZyxlEYVQ2FnKotrrg ssh.pub (RSA)
```

**Comment by wongma7** [comment]
I have discovered an issue that might be causing this. If you generate a key using the app then later import your own private key, the generated public key doesn't get deleted. So there will be a mismatched .ssh_key and .ssh_key.pub file in the app's file and it caused me Auth Failed errors.

If you ever played with the 'generate' option in the app that might be it. (We can test by uninstalling/reinstalling the app.) Otherwise if the keypair works fine outside the app I'm at a loss.

**Comment by bgaluszka** [comment]
Yep, seems like this could be an issue. I've generated keypair before and then imported my own.

**Comment by wongma7** [comment]
The new version 38 should now be out on f-droid. When you get a chance update and then re-import your ssh key and git operations should work.

**Comment by bgaluszka** [comment]
Works :) Thank you.

**Comment by wongma7** [comment]
Great! no problem.
