### ISSUE TITLE
Cannot Use a Directory That Already Exists

### ISSUE THREAD

**Issue by jryan128** [zeapo/Android-Password-Store#161]
I'm using Bit torrent sync to sync my folder to my android, but every time I try to select "External folder" it tells me that it's going to delete everything in it? Is there a way to have it just use the folder?

**Comment by jryan0** [comment]
I can't use file:// for the git repo either.

**Comment by jryan0** [comment]
For now I tricked it by creating the folder with the app, then just populating it after the fact. Still not very friendly for external use.

**Comment by ainola** [comment]
Yeah, I don't really want to have to manually sync all of my passwords with: I'd rather this application work as `pass` does: Just reading the directory and acting on it's current state.

**Comment by ainola** [comment]
Ah, I think this is something that wants to happen in the future:

http://zeapo.com/blog/2014/12/16/Android-Password-Store/

I guess the answer would then be..... "commits welcome"?

**Comment by vshl** [comment]
I've a similar issue while trying to clone an existing repo: http://i.imgur.com/Rk1GY1r.png

This happens with External storage also. It tells me to select a directory. I select an empty directory, and it prompts that the directory already exists.

**Comment by wongma7** [comment]
Even though it says 'remove everything' the app does not actually delete everything in the directory in this version. Not sure if this behavior is intentional. Maybe it is to scare you to confirm that you understand the app will have full "privileges" over the folder you choose and it has the power to delete everything in it e.g. when the user selects 'delete repository' in the options. 

Anyway the desired behavior of using Bittorrent sync/other syncing things to a folder in the sdcard should work fine

**Comment by edrex** [comment]
Confirmed, even though the dialog claims the directory is about to be cleared, it isn't. I also prefer to have some other service handle the syncing (in my case Syncthing). This should be a supported use case.

**Comment by zeapo** [comment]
I have just fixed the mistake and think that you mistakingly used the *Clone existing* rather than *Create New* which were two confusing buttons to start with... 

I've just renamed them into *clone from server* and *use local directory* to indicate that the former is meant to override data on the directory you select using the data from the server. The latter on the other hand, is meant to be used to start from a local directory on your device and configure git later on.
