### ISSUE TITLE
[BUG] does not encrypt to multiple keys

### ISSUE THREAD

**Issue by Rudd-O** [zeapo/Android-Password-Store#1630]
### Describe the bug

When creating new password in device, the other devices to which the password is synced, cannot decrypt the password.

On further inspection, the password is only encrypted to the GPG key of the device, not to the others, despite the presence of a correct `.gpg-id` that works well with `pass` in all other devices.

Password created by Password Store look like this with `file`:

```
[user@ring5-vault .password-store]$ file xxx.gpg 
xxx.gpg: PGP message Public-Key Encrypted Session Key (old)
```

They look lik this when created by `pass` in a UNIX computer:

```
[user@ring5-vault .password-store]$ file xxx.gpg 
xxx.gpg: PGP RSA encrypted session key - keyid: 17DEC231 F7B0B0A2 RSA (Encrypt or Sign) 3072b
```

IOW something is wrong.

### Steps to reproduce

Reproducer:

* Create password in device.
* Observe it cannot be decrypted in other devices because it is not encrypted to multiple keys.

### Expected behavior

Other devices can decrypt passwords.

### Device information

- Device: Pixel 4 XL
- OS: Latest GOS
- App version 1.13.5-fdroid

**Comment by msfjarvis** [comment]
This was previously tracked [here](https://github.com/android-password-store/Android-Password-Store/issues/1461) and according to the replies there it works correctly :shrug:

**Comment by Rudd-O** [comment]
Well, it doesn't work.  I can repro.  We can track in the other bug if you would like.

**Comment by hargut** [comment]
Just had a setup with multiple keys involved and can summarize my experience as:
* Yes, it does work.
* No, it was not fully compatible with pass.

Setup repository encrypted with `pass init keyId1 keyId2`.
On the Phone keyId1 was available with private key, keyId2 only public key.
Decrypting worked as expected, encrypting/saving failed due to a message similar to "unknown id in .gpg-id or not found".

Switching the .gpg-id to reference the key e-mail addresses worked to fix saving/encryption.

Cheers & thank you for developing this great app! :beer:

**Comment by msfjarvis** [comment]
Can you share the redacted contents of your `.gpg-id` file before the change that fixed it? What key identifier type were you using? We are able to parse key IDs, hex fingerprints and email addresses with equal confidence so this is rather surprising.

**Comment by hargut** [comment]
Hi @msfjarvis,

sure, the first try contained the ids of the encryption sub-keys, and looked like:
```
29A6898C06AA3886!
8A3B411E8B5129BA!
```

Where `gpg --list-keys --with-colons '29A6898C06AA3886!' '8A3B411E8B5129BA!' | grep -E ':29A6898C06AA3886:|:8A3B411E8B5129BA:'` prints details like:
```
sub:u:4096:1:8A3B411E8B5129BA:1550094022::::::e::::::23:
sub:u:4096:1:29A6898C06AA3886:1446865283::::::e::::::23:
```

the second try contained, which also did not work:
```
29A6898C06AA3886
8A3B411E8B5129BA
```

the third try referenced the according emails where `gpg list-keys --with-colons '8866AA329A6898C0!' '1E8B58A3129BAB41!' | grep '@'` shows details like:
```
uid:u::::1550094022::52F6A056022110C3231F63B77E1445CCB5862863::Key1 Name (Key1 Comment) <key1@domain1.org>::::::::::0:
uid:u::::1446865283::770CA3F6348D669BB0F31D53A993C5C96EE036C0::Key2 Name (Key2 Comment) <key2@domain2.com>::::::::::0:
```
with the working `.gpg-id` file
```
key1@domain1.org
key2@domain2.com
```

Eventually this is related to using the encryption sub-key id, instead of the main keys id.

The background was that one of the keys contained multiple encryption sub keys, and a specific one should be used for the password store. (Which anyway did not work out as intended. The encryption key selection mechanism of `pass` currently selects all available encryption keys within a matching key. This might also be related to the gpg version and its outputs, but `pass` selects all keys that are returned from the `gpg list-key` operation, and contain an **e** flag).


Have a nice weekend &  best regards,
Harald

**Comment by msfjarvis** [comment]
Thanks a lot, that clears up things. This is an instance of [this](https://github.com/android-password-store/Android-Password-Store/issues/1360) bug which is an unimplemented functionality in OpenKeychain.

**Comment by hargut** [comment]
Yes, indeed that issue describes the same situation & use case. 👍
