### ISSUE TITLE
Get the error "No encrypted data with known secret key found in stream" on any new passwords

### ISSUE THREAD

**Issue by imarkskinner** [zeapo/Android-Password-Store#173]
Upon first running and syncing of my git repo all passwords are accesible no problem, if I add a new password to my server and sync it to my phone then I will get the error "Error from Openkeychain: No encrypted data with known secret key found in stream"

All keys are encrypted/signed with the same gpg key but ones added after the initial setup will never work. Deleting app data and starting over with a fresh setup (same gpg key) will work fine on all current passwords, including those that won't work before data wipe.

**Comment by zeapo** [comment]
do you have multiple keys in openkeychain?

**Comment by cqcumber** [comment]
I have a similar problem: when trying to decrypt any password encrypted to my normally used key I get the "Error from Openkeychain: No encrypted data with known secret key found in stream" error message.  Here is all I tested:
- encrypting a password to my normal key and decrypting with normal key: error message
- encrypting a password to my normal key and decrypting with normal key on my pc: works
- encrypting a password to a newly generated key (OpenKeyChain) and decrypting: works (since this step I have two keys in OpenKeyChain, before it it's one)
- (like imarkskinner) wipe data & get repo with passwords encrypted to my normal key via git and decrypting: error message
maybe the layout of my normal key has something to do with this:
master key SC, subkey E, subkey S (in comparison the newly generated key has: master C, subkey E, subkey S)
I would appreciate any hints to solve this. Thanks!

**Comment by jas4711** [comment]
I see this problem too: it happens for passwords saved with newer versions of 'pass', it seems it now encrypts the passwords to a hidden recipient rather than an explicit key.  Passwords encrypted to explicit keys works fine in Password Store but hidden-recipient-passwords doesn't.  At least if I understand what this bug report is about.

**Comment by zeapo** [comment]
Can you check that your key is selected in the option "Select your OpenPGP
key id" (the last option in crypto)

Le 20 juil. 2016 1:28 PM, "Simon Josefsson" <notifications@github.com> a
écrit :

**Comment by XDjackieXD** [comment]
I have a very similar issue: When I try to create a new password I get the error message `Error from OpenKeyChain: Revoked/Expired key cannot be used for sign or encryption`
My key-layout is also primary CS and subkey E. Decryption of existing passwords works fine.

**Comment by nullterminated** [comment]
I'm having the same problem. I have selected OpenKeychain as the OpenPGP provider, I selected my key, then I selected the OpenPGP Key id. My private key is on a Yubikey Neo, my public key is in the OpenKeychain.

**Comment by lifeisinthemind** [comment]
I'm having this problem too. Its very frustrating. If I encrypt to myself I can decrypt it no problem. But from anyone else I can't. I have used openkeychain and APG with the same problem. Really need this resolved soon.

**Comment by zeapo** [comment]
@lifeisinthemind are you able to decrypt the file directly using OpenKeyChain?

**Comment by nullterminated** [comment]
Good idea @zeapo 

I tried to encrypt to the public key and then decrypt it with the private key on my yubikey and had the same error in OpenKeychain. The odd thing is, this seemed to work in K-9 mail. I can use the private key on the yubikey to encrypt an outgoing message. However, it looks like I have the same error again on incoming encrypted messages. It appears the OpenKeychain knows how to look for the smartcard private key for encryption operations, but only checks the private keys on the android for decryption.

I also tried plugging the yubikey into the phone using an OTG cable, but that only resulted in the yubikey being recognized as a keyboard.

**Comment by zeapo** [comment]
could you replicate this with a new key pair? That would help to write fix for it

**Comment by lifeisinthemind** [comment]
How would I replicate a new key pair? I have not had the experience with
that yet. Just create a new key all together? I have done that and even
used a different email in case my past keys were somehow linked same
problem. I can decrypt a message I write to myself but anyone who has my
public key and writes me I'm unable to do so. I have tried 3 different
people.

**Comment by zeapo** [comment]
Aha, If it's "anyone" then you should open an issue on openkeychain
repository.

Le jeu. 18 août 2016 04:55, lifeisinthemind <notifications@github.com> a
écrit :

**Comment by icewind1991** [comment]
I'm running into the same issue using secret keys stored on a Yubikey Neo, everything works with the same private keys stored on the phone.

I can decrypt the .gpg files trough OpenKeyChain directly using the Yubikey.

**Comment by nullterminated** [comment]
>could you replicate this with a new key pair? That would help to write fix for it

I was able to get it working if I let OpenKeychain generate my PGP key. Somehow it did not work with the key I generated on my laptop. Odd, but my problem here seems solved.

**Comment by lifeisinthemind** [comment]
I'm.not quite sure what that exactly means. I'll Google it up and see what
I can do.

**Comment by jhimanka** [comment]
I have the same problem and it's still unresolved. I created a new GPG key on the Linux workstation that hosts the git repository.  Everything works there and on another macOS machine that has a clone. On the phone, deleting the old repository and cloning it again went ok. I imported the new key to Openkeychain. When I try to set the PGP key in the Pass app, "Select OpenPGP Key id" just flashes. And I cannot decrypt any passwords. The new key is 4096 bit RSA.

**Comment by icewind1991** [comment]
Clearing all data and re-setting up the app fixed the problem for me with using a Yubikey

**Comment by jaumb** [comment]
I got this error with my secret key stored on a yubikey and it went away after inserting the yubikey  and selecting import in the app. Now everything is working well.

**Comment by trmendes** [comment]
Since the last update I'm runnint into the same issue! SOME of my password I'm able to open and see the content and most of them I get this error: "No encrypted data with known secret key found in stream"

Password Store Version: 1.3.1 (from F-Droid)
OpenKeyChain Version: 5.2 (from F-Droid)
Android Version: 8.1.0 (LineageOS 15.1)

**Comment by trmendes** [comment]
@zidhuss Is there an easy way to do it? I have way to many password to re-encrypt one by one.

- I'm using the same key on my phone and on my linux machine. On Linux I have no problem opening/editing any of the keys.

**Comment by zidhuss** [comment]
I believe all you have to do is run `pass init <new gpg key>` with your new gpg key on the command line version.

**Comment by nshenry03** [comment]
I had the same problem, on my computer, I had added `throw-keyids` to `~/.gnupg/gpg.conf` which forced gpg to not put the recipient key IDs into the encrypted gpg files for pass (which made it so that openkeychain couldn't open/decrypt the files :/ ...  

To fix existing keys, from `~/.password-store`
```bash
cd ~/.password-store

for gpg in $(find . -name *.gpg | fgrep -v Marketplace)
do
  echo -e "\n\n${gpg}\n---------------------------------------------"

  gpg2 --decrypt ${gpg} 2>/dev/null \
  | gpg2 --no-throw-keyids --encrypt -r 0x2E6AAA57E7D90EF6 --output /tmp/${gpg##*/}

  mv /tmp/${gpg##*/} ${gpg} 
done

git commit -a -m "--no-throw-keyids"
git push
```

**Comment by gnumoksha** [comment]
> I had the same problem, on my computer, I had added `throw-keyids` to `~/.gnupg/gpg.conf` which forced gpg to not put the recipient key IDs into the encrypted gpg files for pass (which made it so that openkeychain couldn't open/decrypt the files :/ ...

Thank you! You're a genius!

I had some trouble with the script so I've made some modifications in order to get it working in a more generic way and to fail fast if something goes wrong:
```bash
#!/bin/bash
set -euo pipefail
export IFS=$'\n\t'

export KEYID=0xE724F606EFFF66F7 # Put your key id here

GPG=$(which gpg) # the path for the gpg program
PASSWORD_STORE_DIR=${PASSWORD_STORE_DIR:=$HOME/.password-store}
TEMP_DIR=$(mktemp --directory)

for path in $(find ${PASSWORD_STORE_DIR} -iname '*.gpg'); do
  echo "Processing ${path}"
  temp_file="${TEMP_DIR}/${path##*/}"

  ${GPG} -q --decrypt "${path}" | ${GPG} --no-throw-keyids --encrypt -r $KEYID --output "${temp_file}"

  mv -f "${temp_file}" "${path}"
done

echo
echo "Creating git commit with all the changes"
read -n 1 -s -r -p "Press any key to continue, ctrl+c to stop"
echo
git commit -a -m "Adding key ids (i.e. gpg --no-throw-keyids)"

echo
echo "Pushing the commit"
read -n 1 -s -r -p "Press any key to continue, ctrl+c to stop"
echo
git push
```

I would like Android Password Store has a better error message for this.

BTW I've disabled `throw-keyids` in my `gpg.conf` as it seems to be a trouble maker rather than a useful thing to my use of GPG.

**Comment by zeapo** [comment]
@gnumoksha Would you mind opening a PR with your script in the `contrib` directory? That would be great :)

**Comment by holderl5** [comment]
I made sure the  --no-throw-keyids  was set and then ran the following:
pass init KEYID

**Comment by grobx** [comment]
This command would also fix it:

```sh
PASSWORD_STORE_GPG_OPTS="--no-throw-keyids" pass init $KEYID
```
