### ISSUE TITLE
[FEATURE] Password-Store flavor without Internet permission

### ISSUE THREAD

**Issue by nikitabobko** [zeapo/Android-Password-Store#1770]
### Is your feature request related to a problem? Please describe.

Even though `Password Store` app is open source, users can't be sure that the app doesn't leak passwords. Not everyone is ready to inspect the source code and users can't be sure that the version of the app is published to F-Droid/Google Play is built from the same sources we observe on GitHub.

### Describe the solution you'd like

It would be cool if `Password Store` had an alternative flavor in F-Droid/Google Play without Internet permission. This way users could be sure that the app doesn't leak passwords. Yes, such a flavor wouldn't have git synchronization feature but users are free to use other options: manual file synchronization or git in Termux

### Describe alternatives you've considered

The alternative would be:
1. Next version of Android has a feature of restricting internet access (right now, stock Android 12 doesn't have such a feature)
2. Maintain my own internet-permission-free fork

**Comment by msfjarvis** [comment]
Users can be 100% sure that our code corresponds to the actual APK, because we opted into F-Droid's verification program and they compare their generated APKs with what I publish to GitHub Releases to ascertain that. They can also just build the app themselves.

I'll recommend you maintain a fork, We're not making any changes like this to APS.
