### ISSUE TITLE
[FEATURE] Allow system backups

### ISSUE THREAD

**Issue by bw9ubwo** [zeapo/Android-Password-Store#1792]
### Is your feature request related to a problem? Please describe.

I use Lineage OS with Seedvault to back up installed apps to my Nextcloud. But Password Store doesn't allow backups.

I don't know how the Google backup encrypts data, but the way seedvault dose, it should be safe enough to store the thing online.

### Describe the solution you'd like

Allow Backups

https://developer.android.com/guide/topics/data/autobackup#EnablingAutoBackup

### Describe alternatives you've considered

Allow Backups

**Comment by msfjarvis** [comment]
The specific functionality you're looking for is _auto_ backup, which does not allow users to opt out of backing up specific apps when used with Google Drive. This was discussed in the past (https://msfjarvis.dev/aps/issue/235) and we made the decision to explicitly opt out because users more often than not are against their store being uploaded to Google Drive automatically.
