### ISSUE TITLE
[BUG] Incorrect translation in autofill popup, can't find on Crowdin

### ISSUE THREAD

**Issue by vera** [zeapo/Android-Password-Store#1842]
### Describe the bug

In the autofill popup (e.g. in the browser), the German translation of "Search in store" is "Suche im Shop", which is wrong (store != shop). I can't find this string on Crowdin to suggest another translation.

### Steps to reproduce

1. Set phone language to German
2. Open e.g. browser and click on any login form field so the autofill popup appears
3. See incorrect translation

### Expected behavior

See correct translation, e.g. "Im Store suchen..." or "Im Speicher suchen..."

### Device information

- App version: 1.13.5

**Comment by msfjarvis** [comment]
The string in question was refactored in https://msfjarvis.dev/aps/1d13a1fbd658 to read 'Search entry', the translation for which you should be able to find on Crowdin. The commit did not make the cut for our patch releases so unfortunately the Play Store build still contains the erroneous translation.

As of now, we're unable to update the app on Play Store without cutting out the external storage feature so your only option would be to use the [snapshot builds](https://docs.passwordstore.app/docs/Users/release-channels) which contain all the development work that has happened since the last stable release.
