### ISSUE TITLE
[FEATURE] Use url field of entry for autofill

### ISSUE THREAD

**Issue by mimi89999** [zeapo/Android-Password-Store#1954]
### Is your feature request related to a problem? Please describe.

I'm storing my passwords in files with arbitrary names, but with the `url:` field that should indicate which site they should be used on. Currently, autofill isn't using this filed, but requires a special file naming convention.

### Describe the solution you'd like

Password Store should read all password files, search for that field and then create a map domain:password_file

### Describe alternatives you've considered

None

**Comment by msfjarvis** [comment]
We use the file name setup because that's what we've found the convention to be in the pass ecosystem. Implementing any kind of mapping based on a field in your passwords will require an extremely brittle infrastructure that will worsen the user experience for everyone and not be reliable.

I'll note down my reasons for not implementing this below

- Decrypting all passwords even if they're as low as 30 to 50 individual files can take multiple minutes due to how OpenKeychain and Password Store interface with each other as well as just the overhead of decrypting a file.

- For Git-based repositories it would require a re-index after every single Git operation which will make a simple pull operation take many times longer than it would otherwise.

- For non-Git repositories we will be forced to store an internal representation of the repository tree and diff it against the actual on-disk state every time the app is used and then decrypt and re-index all the changed/new files regardless of what the user actually wanted to do in the app. This is extremely error prone and it introduces a completely unnecessary sync aspect to the app which is a hard problem to solve correctly.

I understand the motivations to want to use a URL field but it is simply impractical to implement for us. Password Store will internally create mappings between URLs and the passwords you choose when you autofill into them so you can opt to accept the one-time overhead of having to manually search when using Autofill on a page and from then on Password Store will remember your pick.
