### ISSUE TITLE
[FEATURE] Add monochrome icon to round app

### ISSUE THREAD

**Issue by rianadon** [zeapo/Android-Password-Store#2089]
### Is your feature request related to a problem? Please describe.

This app has been absolutely amazing for accessing my passwords, and I have it easily accessible on my home screen.

It's been bothering me that on my homescreen (the stock Pixel launcher when using round icons & themed icons), the app icon shows up in color while other icons are monochrome.

<img src="https://user-images.githubusercontent.com/18223213/186745271-f99fb966-619b-43a4-83bc-b248f0f4c981.png" width="300" />

### Describe the solution you'd like

I found that https://github.com/android-password-store/Android-Password-Store/blob/develop/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml already has a monochrome icon specified, while https://github.com/android-password-store/Android-Password-Store/blob/develop/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml does not.

I was wondering if the fix would be as simple as adding this `<monochrome>` tag to the `ic_launcher_round.xml` file would be enough to fix the issue.

### Describe alternatives you've considered

If the icon is incompatible, the icon may need to be resized or cropped? I'm not familiar with android development, so I don't know which of these options is needed.

**Comment by msfjarvis** [comment]
The round icon is typically not used on the newer platforms and the main adaptive icon is preferred instead. I'm pretty sure the problem is that you're on v1.13.5 which does not have the monochrome icon in the first place.

You could use the [snapshot builds](https://docs.passwordstore.app/docs/users/release-channels/) to get access to the monochrome icon, but those builds no longer contain OpenKeychain support which is a dealbreaker for most users until all the parity work listed in #1523 is completed.
