### ISSUE TITLE
Reset app to clean slate?

### ISSUE THREAD

**Issue by eterps** [zeapo/Android-Password-Store#212]
For some reason Android-Password-Store is not working anymore (no passwords are shown).
Is it possible to reset to 'factory settings'? More specifically can I remove some folders with a file manager to return the app to a clean slate?

**Comment by danielvandenberg95** [comment]
This is not something that should (in my opinion) be covered by the Password Store. Making sure it doesn't happen is, resolving this kind of issues is not.

For resetting any data on any app, please follow the instructions as given on http://www.cnet.com/how-to/how-to-clear-app-cache-and-app-data-in-android-6-0-marshmallow/ or http://www.phonearena.com/news/How-to-clear-app-cache-and-app-data-on-Android_id67252 for Android 6 and Android 5 respectively.

**Comment by zeapo** [comment]
@eterps Sorry to hear that the app no longer works for you.

Could you describe how that happened? Was it an update? Or did you uninstall then reinstall the app? If it is the former then it should not have happened, if it's the latter then it is normal as we store the passwords in the data directory of the application so that nothing can access them except the app itself.

If you'd like to keep your settings and just remove the directory that used to contain the passwords, then you can go to **options** -> **delete repository**.
If you'd like to have an absolutely clean app, then follow the links given by @danielvandenberg95

**Comment by eterps** [comment]
Thanks, I will try again ASAP. I can't say what happened, it seems that the app doesn't given any error messages when things can't be pulled/pushed/synced from a repo, but I will try again.
