### ISSUE TITLE
[FEATURE] add OTP code generation support

### ISSUE THREAD

**Issue by juchem** [zeapo/Android-Password-Store#2126]
### Is your feature request related to a problem? Please describe.

I can't log on to websites that use 2FA with just the password.

### Describe the solution you'd like

Many websites require 2FA on top of passwords

`pass` on Linux has support for otp through an extension which adds an OTP link to the secret

Rather than relying on separate apps for 2FA support, it would be a natural extension to use APS for the whole thing

As a first step, being able to generate 2FA codes for existing OTP links should already be a great help.

A follow up would then to be able to add OTP links to the secrets.

### Describe alternatives you've considered

I'm currently using the `pass-extension-otp` solution on Linux for 2FA, but that's no good when I'm away from my computer.

There are separate apps for 2FA, but that defeats the purpose of having a single secret store.

**Comment by msfjarvis** [comment]
2FA via TOTP has been supported for years, I don't know what this issue is for.

**Comment by BoostCookie** [comment]
TOTP has always worked for me and suddenly it does not anymore. There was not even an update.
Is there any info I can provide to debug this?

**Comment by msfjarvis** [comment]
> TOTP has always worked for me and suddenly it does not anymore. There was not even an update. Is there any info I can provide to debug this?

TOTP works in the current development builds so there's nothing to debug really. If you'd like to file a new issue with the details requested in the issue form I can see if there's some unknown edge case that's causing breakage.

**Comment by BoostCookie** [comment]
I've found the issue. This app does not like it when the otp line is written with a space. So
`otpauth://totp/testcompany?secret=bl5iltld2panxcgbamwazvf5nwicmfwk&issuer=testuser`
works, but
`otpauth: //totp/testcompany?secret=bl5iltld2panxcgbamwazvf5nwicmfwk&issuer=testuser`
does not.
This is unfortunate since the latter one is the way ~[pass-otp](https://github.com/tadfisher/pass-otp#readme) saved my otp secrets~ [gopass](https://github.com/gopasspw/gopass/) changed my files to upon reencryption.

**Comment by msfjarvis** [comment]
> I've found the issue. This app does not like it when the otp line is written with a space. So `otpauth://totp/testcompany?secret=bl5iltld2panxcgbamwazvf5nwicmfwk&issuer=testuser` works, but `otpauth: //totp/testcompany?secret=bl5iltld2panxcgbamwazvf5nwicmfwk&issuer=testuser` does not. This is unfortunate since the latter one is the way ~[pass-otp](https://github.com/tadfisher/pass-otp#readme) saved my otp secrets~ [gopass](https://github.com/gopasspw/gopass/) changed my files to upon reencryption.

One is a valid URI and the other is made up bullshit from `gopass` so... 🤷🏼 

I would recommend opening an issue with `gopass` and seeing if they're willing to fix it, because the conventions I have seen for TOTP in the `pass` ecosystem are of only two formats

- `totp: <secret>`
- `otpauth://totp/<issuer>?secret=<secret>`

If they insist they're not wrong then I can probably add a workaround to APS.

**Comment by BoostCookie** [comment]
> I would recommend opening an issue with gopass

No, I'm done with them. They sure have created lots of problems by forcing everyone on some weird formats
https://github.com/gopasspw/gopass/issues/1585
https://github.com/gopasspw/gopass/issues/1594
https://github.com/gopasspw/gopass/issues/1600
https://github.com/gopasspw/gopass/issues/1602
https://github.com/gopasspw/gopass/issues/1607
https://github.com/gopasspw/gopass/issues/1612
instead of keeping it simple and letting the user write the text file.
I will switch back to pass. Sorry to have bothered you.
