### ISSUE TITLE
Password show time

### ISSUE THREAD

**Issue by rti** [zeapo/Android-Password-Store#228]
When copying two passwords to the clipboard before the password show time of the first password copy expires, the second copy does not reset the timer. 

Reproduce:
 * set password show time to 30s
 * copy one password to clipboard
 * wait 20s
 * copy another password to the clipboard
 * wait 20s
 * paste the clipboard

Expected behavior: second password is pasted
Actual behavior: "MyPasswordIsDaBest!" Is pasted

**Comment by zeapo** [comment]
On the technical side, the issue is a little more complicated than just resetting the timer. Each copy will create an async task to clear the clipboard. The second copy creates a second asynchronous task. The first task will clear the clipboard when it ends, so 30 seconds after the first copy. Hence, the second task has to find the first task and cancel it.

**Comment by danielvandenberg95** [comment]
Would it be a better idea (considering clipboard logs) to instead of cancel the other async task, make it execute immediately, even before writing the new password to the clipboard?

**Comment by zeapo** [comment]
The second copy is executed immediately when the user press copy. The issue is that the previous async task is still running, so it will clear the clipboard.

**Comment by danielvandenberg95** [comment]
I know, let me try to outline what I mean better. (Assume timeout is set to 40 seconds)
Current situation:
Press copy A
Copy password A
Timer A starts
20 second wait

Press copy B
Copy password B
Timer B starts
20 second wait

**Timer A fires and erases everything**
20 second wait
**Timer B fires and erases everything**

----------------------
Proposed situation:
Press copy A
Copy password A
Timer A starts
20 second wait

Press copy B
**Timer A gets canceled**
Copy password B
Timer B starts
40 second wait

**Timer B fires and erases everything**

----------------------
My proposed answer: (Not sure if it's easily doable, depends on how the timer is implemented, didn't look into that.)

Press copy A
Copy password A
Timer A starts
20 second wait

Press copy B
**Timer A gets forced to fire and erases everything**
Copy password B
Timer B starts
40 second wait

**Timer B fires and erases everything**

----------------------
I hope this gets my idea across

**Comment by zeapo** [comment]
I see! How would we force it to execute?

The scheme of things right now is:
- Copy password A
- Create AsyncTask
  - Sets its inner timer
  - After 45 sec, the AsyncTask will execute `onPostExecute` and clears the cliboard.

Also, if we are able to find the currently running async task, wouldn't be easier to just call `cancel()` rather than tinker with the inner timer for it to execute the `onPostExecute`?

The current issue for both cases, is how to find the previous task? Do we keep a `static` for the copy tasks so that we only have a single one running at any moment? That would work I guess.

**Comment by gschwaer** [comment]
> Do we keep a `static` for the copy tasks so that we only have a single one running at any moment? That would work I guess.

Do you mean the copy task or the timer task? To just change the timer task to be `static` should be sufficient, i think.

**Comment by zeapo** [comment]
Yes the timer, typo :)

Le 16 oct. 2016 11:34 PM, "Gero Schwäricke" <notifications@github.com> a
écrit :

**Comment by zeapo** [comment]
I've used a mix of different solutions. I let the first timer task finish, but tell it not to clear the clipboard.

Each time the user copies a password, the previous one is set to not clear the clipboard. We do not need to track all the tasks that existed before.

**Comment by rti** [comment]
Thanks a lot for the super fast fix and the great app!
