### ISSUE TITLE
Travis is busted?

### ISSUE THREAD

**Issue by danielvandenberg95** [zeapo/Android-Password-Store#231]
My pull request suddenly gets marked by Travis as unable to build. Something with the licences, 

   > You have not accepted the license agreements of the following SDK components:
     [Android SDK Build-Tools 23.0.3, Android SDK Platform 23].
     Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
     Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

**Comment by zeapo** [comment]
I did ^_^

That happened when I changed the build tools in cb7f9c8529d82a6229c2679319a259ea986cf63b
The issue is that even an update to `.travis.yml` didn't solve it (yet): 36b5e276037d32d70fa39a9fc020a6457c848840 these changes should have fixed the license issue, but didn't. I will check why later, unless you have an idea ;)

**Comment by zeapo** [comment]
https://github.com/zeapo/Android-Password-Store/pull/232 fixes it

**Comment by zeapo** [comment]
The build is green once again
