### ISSUE TITLE
[BUG] App is unavailable on the Google Play Store

### ISSUE THREAD

**Issue by Zwyx** [zeapo/Android-Password-Store#2417]
### Describe the bug

The app appears to be requiring Android 6 and up. I have a Google Pixel 4a with Android 13. Still, I cannot install the app: the Play Store shows `This app is not available for any of your devices`.

It's not a critical issue as I can still manually install the APK, but I thought I'd report it here.

(Also, I'm in Australia, in case the region has something to do with it.)

### Steps to reproduce

I just opened this page: https://play.google.com/store/apps/details?id=dev.msfjarvis.aps

### Expected behavior

App available for install.

### Device information

- Device: Google Pixel 4a
- OS: Android 13
- App version: -

**Comment by msfjarvis** [comment]
I'm aware of it, unfortunately there's nothing I can do about this that will not break the app for a subset of its users. There's a new major release in development currently that removes the feature in question but there's still a lot of work left to do so it doesn't make sense to put it on Google Play right now.

**Comment by Zwyx** [comment]
Thank you for taking the time to answer. Out of curiosity, and if it's super quick for you to explain, why is this feature causing this?

**Comment by msfjarvis** [comment]
> Thank you for taking the time to answer. Out of curiosity, and if it's super quick for you to explain, why is this feature causing this?

Android's tightening down on storage access for apps due to rampant abuse which makes the "normal" `java.io.File` APIs obsolete for anything that involves dealing with user-accessible storage.

APS has had a feature for many years that allows users to keep their pass store in their phone's public storage and sync it using alternative mechanisms like Syncthing. Continuing to support that on the target SDKs Google Play now requires would involve making the app essentially duplicate a whole bunch of things to deal with stores in hidden storage and those in public storage, which is entirely too much work for a single developer who doesn't even use the feature in the first place :)

**Comment by Zwyx** [comment]
Ah interesting! It all makes sense. Thanks again :slightly_smiling_face:
