### ISSUE TITLE
[BUG] Importing from local offline folder does not import into private memory

### ISSUE THREAD

**Issue by ghost** [zeapo/Android-Password-Store#2456]
### Describe the bug

When importing my passwords, I'm prompted to choose between online repo or local external database. If choosing offline, I'm forced to have it as external folder for all subsequent use of the app, instead of importing the local repo into app private memory. I find no issues already opened on this, neither I find any reason to this asymmetrical behaviour between online and offline import. It is already strange the very moment it asks to "clone remote repo" but to "create local repo". Offline backup, apart from being more secure, it's just way more easy to setup.

### Steps to reproduce

1. At fresh install, launch app and select "Let's go", "create local repo", and then if I select "hidden", I can only create a new repo, not import the existing one; I have to select "SD-card" (even though it allows all memory, should be just "local memory", since I can use SD as well as just copying files from any other source into internal memory) and select the folder, but from then I cannot import into app hidden memory. Not fundamental, but also not understandable.

### Expected behavior

Importing should be as simple as exporting: select folder, import into memory,done. I then would delete original folder.

### Device information

- Device: all devices
- OS: all androids
- App version: 1.13.5

**Comment by msfjarvis** [comment]
The app does not offer this functionality because nobody has asked for it and it doesn't seem particularly useful.

The idea here is that Password Store is not _meant_ to be a read-only app, and prioritises the ability to sync back edits to a different canonical copy of the store. When you clone a remote repo you get that ability for free via Git, and if you dislike Git for any reason, you can choose to use [Syncthing](https://syncthing.net/) via the support for public storage.

There is fairly little value to derive by copying in the repository from your device's storage into Password Store's internal folder since there's no easy way to integrate future external updates or push changes made through Password Store out.

Re: importing a remote repo, remote doesn't imply "over the Internet". I and many others simply use our computers as the Git remote to do pulls and pushes on LAN or more recently through [Tailscale](https://tailscale.com/). Git needs no extra configuration for this functionality.

If you feel strongly about this feature you're free to raise a PR and I will try to review it, but I have limited bandwidth and no motivation to use that time on this.

**Comment by ghost** [comment]
Thanks for the interesting and detailed response.

I wish to elaborate, but I won't be requesting anything if you're not interested. Obviously, I would say.
- I never had the idea of Password Store to be a read-only app, don't get why this has come to your mind from my words. I use it with frequent backups so it is correctly designed to be able both to to start from reading a backup, and to write new stuff into the store. This, if I correctly understood  what you were meaning with "read-only" app.

- The LAN repo is an idea I can understand, but it's just for the tech savvy. I used Syncthing for quite a while but abandoned it because it's designed very bad I'm the enduser utilisation. I was way faster syncing manually that programming Syncthing folders and behaviour, and that's not true only in very complicated backups (probably for people who works with programming). Git I don't know so I won't comment. But the point is: the password storage is a single backup file, encrypted. Why a lan sync through repo, git or whatever program, is considered faster or easier than just a simple, single file copy? It may probably be convenient just for those people who already uses all that stuff, but while that's a minority, just pretty everyone uses passwords with phones and should get to a user friendly password manager for security reasons (best secure practice - a different complicated password for every site) and ease-to-use passwords. I think the program should prioritise non tech savvy people, especially with the ease of use of a single backup file. The already very convenient usage design made me think the program was for everyone.
But obviously, I may be wrong, and if this feature has no use or value for you, to me there's no problem.

- "fairly little value by copying into PS internal folder"; "no easy way to integrate future external updates or push changes"
I did not get this part, since I believe push changes are updates to the app, what has this to do with the passwords stored? And, in the end, maybe I was misleaded by the suggestion inside the program, where it was stated that internal memory was considered more secure.

**Comment by msfjarvis** [comment]
> Thanks for the interesting and detailed response.
> 
> I wish to elaborate, but I won't be requesting anything if you're not interested. Obviously, I would say.
> 
> * I never had the idea of Password Store to be a read-only app, don't get why this has come to your mind from my words. I use it with frequent backups so it is correctly designed to be able both to to start from reading a backup, and to write new stuff into the store. This, if I correctly understood  what you were meaning with "read-only" app.

The app itself cannot sync anything out if it absorbs your store into private storage, and you'd have to continuously keep taking backups and re-importing the store to keep it in sync if you're also using the store on a different machine so if that workflow works for you then the read-only bit doesn't come into consideration.


> * The LAN repo is an idea I can understand, but it's just for the tech savvy. I used Syncthing for quite a while but abandoned it because it's designed very bad I'm the enduser utilisation. I was way faster syncing manually that programming Syncthing folders and behaviour, and that's not true only in very complicated backups (probably for people who works with programming). Git I don't know so I won't comment. But the point is: the password storage is a single backup file, encrypted. Why a lan sync through repo, git or whatever program, is considered faster or easier than just a simple, single file copy? It may probably be convenient just for those people who already uses all that stuff, but while that's a minority, just pretty everyone uses passwords with phones and should get to a user friendly password manager for security reasons (best secure practice - a different complicated password for every site) and ease-to-use passwords. I think the program should prioritise non tech savvy people, especially with the ease of use of a single backup file. The already very convenient usage design made me think the program was for everyone.
>   But obviously, I may be wrong, and if this feature has no use or value for you, to me there's no problem.

Stores are not a single file, they're a full file tree. `pass` puts individual passwords in their own files, not into a database like how Keepass does it.

I would prioritize non tech savvy people, but GPG requires a PhD and blood sacrifice to wield correctly so I take liberty with some things. If I wanted to make a password manager for everyone, it would not be this one.

If you're looking for ease of use, I can recommend [Keepass](https://keepass.info/) and [Bitwarden](https://bitwarden.com/).


> * "fairly little value by copying into PS internal folder"; "no easy way to integrate future external updates or push changes"
>   I did not get this part, since I believe push changes are updates to the app, what has this to do with the passwords stored? And, in the end, maybe I was misleaded by the suggestion inside the program, where it was stated that internal memory was considered more secure.

The store is indeed more secure when in the internal storage. When I said "future external updates", I meant incoming changes to the store itself from a copy held elsewhere rather than changes to the app which would be deployed as updates as you correctly figured. I've explained the rest in the first point.


I don't believe this is a viable feature to implement in the app, nor does Password Store seem like a fit for your needs so I'm going to go ahead and close this issue.
