### ISSUE TITLE
[BUG] Custom port in git http url not supported

### ISSUE THREAD

**Issue by viric** [zeapo/Android-Password-Store#2494]
### Describe the bug

If the git server url is http with a port (http://1.2.3.4:1234) the program suggests to prepend ssh:// in front.
It says "Potential problematic url, click Ok to fix" and, moreover, there is no other option than click Ok. Then it prepends ssh://.

### Steps to reproduce

1. Go to 'Edit Git server settings'
2. Type an http url with port 'http://1.2.3.4:1234/'
3. Accept
4. See error complaining about potential wrong URL, forcing to Ok

### Expected behavior

Accept the url normally. It is well formed.

I guess the aid is meant for some non-http urls; even in that case, the "fix" of prepending ssh:// should be optional.

### Device information

- OS: Android 13
- App version: 1.13.5

**Comment by msfjarvis** [comment]
This should be relatively straightforward to fix, the code that's failing is [here](https://github.com/android-password-store/Android-Password-Store/blob/ff372c0c9757db2a9d7d17efbd0f1b124c917c9e/app/src/main/java/app/passwordstore/ui/git/config/GitServerConfigActivity.kt#L105-L109).

**Comment by viric** [comment]
What I want to do is to be able to use a git server that I just run in my desktop. Be it "git daemon" (git:// is disallowed) or "git instaweb" (http doesn't work unless on port 80).

Those two paths not working leaves me with no git clone possible, I think.

**Comment by msfjarvis** [comment]
> What I want to do is to be able to use a git server that I just run in my desktop. Be it "git daemon" (git:// is disallowed) or "git instaweb" (http doesn't work unless on port 80).
> 
> Those two paths not working leaves me with no git clone possible, I think.

You can do it via SSH but yes if you're trying to use HTTPS then it is currently not possible.

**Comment by viric** [comment]
I'd be happy with http or git, which I cannot use.
As these are not working I ended up using ssh with a command="git-shell ..." parameter in the authorized_keys, but it annoys me that I have to give shell access to my account to password store, for a simple git sync.

Fixing this http:// port bug would be good.

**Comment by swer42** [comment]
It appears that you have encountered a bug in the program related to handling Git server URLs with ports. When you input an HTTP URL with a port (for example, http://1.2.3.4:1234/), the program suggests that you prepend "ssh://" to the URL and displays a message stating "Potential problematic URL, click Ok to fix." Unfortunately, there is no option other than clicking "Ok," which results in the program automatically adding "ssh://" to the URL.

To reproduce the behavior, you can follow these steps:

Go to the 'Edit Git server settings' section in the program.
Input an HTTP URL with a port, for example, 'http://1.2.3.4:1234/'.
Accept the input.
You will see an error message that raises concerns about the URL's potential correctness and prompts you to click "Ok."
The expected behavior should be that the program accepts the well-formed URL without any issues. It seems like the program is incorrectly suggesting the addition of "ssh://" even for HTTP URLs with ports, where such a modification is unnecessary.

**Comment by cizordj** [comment]
I have a self hosted git server that runs on port 8443 because my ISP doesn't allow me to use 443 and I can use pass everywhere except on Android.

Here is an example URL:
`https://something.example.com:8443/user/pass-repo.git`

It works on the command-line (Linux) but it doesn't work on Android.

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
