### ISSUE TITLE
[BUG] No option to select which key to decrypt with

### ISSUE THREAD

**Issue by svvac** [zeapo/Android-Password-Store#2773]
### Is your feature request related to a problem? Please describe.

When decrypting a file with multiple recipients for which APS has the secret key:

- The password prompt does not indicate which key password is to be entered
- There is no way to select the key to use

### Describe the solution you'd like

- Display the key identity in the prompt
- When multiple keys are available, allow the user to select which key to use for decryption

### Describe alternatives you've considered

n/a

### Additional context

version 6223d1b9e1d21e2e0f2066df71b8da3b4d16b295 (snapshot, free)

**Comment by msfjarvis** [comment]
This aspect of the app can definitely use some improvement. Currently the app will go through each identifier it parses from your `.gpg-id` file and attempt to decrypt using the provided passphrase and the corresponding key for that identifier so it'll _probably_ work but the user experience is nonsensical.

If you can set up an example pass repository for the multiple keys use case similar to [pass-test](https://github.com/android-password-store/pass-test) it'll make my job somewhat easier, otherwise I can do it when I find time to work on this.

**Comment by svvac** [comment]
See android-password-store/pass-test#1 for the requested testing files.

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
