### ISSUE TITLE
[BUG] passphrase caching silently doesn't work when no device lock is enabled

### ISSUE THREAD

**Issue by Villemoes** [zeapo/Android-Password-Store#2783]
### Describe the bug

I tried enabling passphrase caching, but that didn't have any effect. I was playing around on a mostly empty phone I use for experiments, and it doesn't/didn't have any device unlock mechanism enabled. Configuring the phone to require a pattern did make the passphrase caching work.

### Steps to reproduce

1. Go to the phone's settings, disable all device lock/unlock features
2. Go to the app's settings, enable passphrase caching
3. Every password unlock requires one to enter the passphrase

### Expected behavior

The app shouldn't allow passphrase caching to be enabled, or at least issue a warning that it's not supported, when there's no device lock mechanism enabled. But I don't know if the app can detect or query that.

Somewhat related: It would be really nice if one could set a time (a few minutes) for which the passphrase would be unlocked, so one doesn't need to provide the device unlock for every use of the gpg key. With such a timeout, perhaps one could even allow passphrase caching even without a device lock enabled.

### Device information

- Device: Motorola edge 30 pro
- OS: Android 13
- App version: 2b93b49

**Comment by msfjarvis** [comment]
Hm yeah this needs to do feature detection ahead of time.

I wish I could add timeouts but the current implementation writes the passphrase to an encrypted key-value store on disk and reads it off there when a cached passphrase is requested so there is nothing in particular to time out.

Authentication is requested every time because while there is a small buffer duration where an app can access a secret key held by the system after a successful authentication event, the app can't tell if it is within that period without attempting to access the key so it's simply the safer choice to always authenticate. I might look into improving this in the future.
