### ISSUE TITLE
When the repository refuses the push, nothing happens

### ISSUE THREAD

**Issue by zeapo** [zeapo/Android-Password-Store#280]
# To reproduce
- From another computer push to the repository
- Add a new password in the Android app, try to push

# What happens
The progress dialog disappears as if everything went  OK

# What should happen
A toast should tell the user that the push failed with the exact error message

**Comment by hughdavenport** [comment]
I think I just came about this, had pushed on laptop yesterday one new pass/commit, then didn't pull in android app. Today I added a few passwords in android app, tried push, nothing happens (looks like it worked fine), tried sync, and tried pull/push, pull/sync/push, and all seemed like the worked, but nothing happened.

**Comment by Tunous** [comment]
I think I am also experiencing this issue. Similairly I'm unable to pull/push or synchronize. Performing any of these actions works as if they were successful but in reality nothing happens.

Is it possible to find out what is the error or access the repository through other git applications and try to synchronize from there? Because right now I'm stuck not being able to access new passwords added through the app on my pc.

**Comment by hughdavenport** [comment]
Is there anything we can do to help? Kinda a deal breaker atm. If you point me to where in the code the issue might be I can have a poke and send a PR

**Comment by wongma7** [comment]
see here https://github.com/zeapo/Android-Password-Store/blob/master/app/src/main/java/com/zeapo/pwdstore/git/GitAsyncTask.java#L38, errors should be bubbled up doInBackground -> onPostExecute -> onTaskEnded.
