### ISSUE TITLE
[BUG] App crashes on Pixel 7 + Android v14

### ISSUE THREAD

**Issue by nilskuhn** [zeapo/Android-Password-Store#2835]
### Describe the bug

Since I updated Android on my Google Pixel 7 to version 14, the app crashes on start. The only way to start it successfully is de- and re-install it. Afterwards, I can configure my repo in the app, create a new ssh key, add it to my git server and the app works. But only until it gets closed once. Afterwards, I cannot start it again. The app window just flickers for some milliseconds and I don't see anything.

I attached a video, please let me know, if any further information would be helpful.
Thanks in advance, Nils

### Steps to reproduce

1. Install the app.
2. Try to start it.

### Expected behavior

The app starts and works.

### Screenshots

https://github.com/android-password-store/Android-Password-Store/assets/1001134/0f357431-5b46-475a-84e5-494e2cea66a6

### Device information

**Phone model:** 
Pixel 7 from 2022, Hardware version MP1.0
**Android-Version:**
14, latest security update from december, 5th 2023
**Baseband-Version:**
g5300q-230927-231102-B-11040898,g5300q-230927-231102-B-11040898
**Kernel version:**
5.10.177-android13-4-00003-ga7208022a7ea-ab10815828
#1 Fri Sep 15 16:40:54 UTC 2023
**Build-Number:**
UQ1A.231205.015

**Comment by msfjarvis** [comment]
Thanks for the detailed bug report. The app isn't crashing but in fact the biometric prompt is hitting a platform bug in Android 14 that causes the prompt to act as if the user dismissed it, which causes APS to close itself. That's why you see the flickering effect, the darkened screen overlay is in fact APS trying to launch. 

We're tracking the issue at https://github.com/android-password-store/Android-Password-Store/issues/2802
