### ISSUE TITLE
[FEATURE] Reencrypt passwords after updating .gpg-id

### ISSUE THREAD

**Issue by jviki** [zeapo/Android-Password-Store#2837]
### Is your feature request related to a problem? Please describe.

I use Password Store on my phone. I'd like to export all the passwords to my PC. However, all passwords are encrypted with a key resident to my phone. I have imported my PC public key into the OpenKeychain, edited the `.gpg-id` file to contain the fingerprint of my PC key. New passwords are now encrypted with the PC key. However, the old ones are still inaccessible:

```
PASSWORD_STORE_DIR=`pwd` pass show web/google.com
gpg: public key decryption failed: No secret key
gpg: decryption failed: No secret key
```

I tried the feature Misc/Export passwords but the situation is exactly the same. Old passwords were not reencrypted with the new GPG key. What can I do?

### Describe the solution you'd like

I'd expect to have a button in the app itself that would reencrypt passwords on demand. Management of the .gpg-id file would be a great bonus as well but not needed.

### Describe alternatives you've considered

If a workaround exists, I'd expect some hint in github Wiki or somewhere that explains how to force Password Store on Android reencrypt my password files.

**Comment by msfjarvis** [comment]
The app does not offer to do a bulk re-encrypt of stores because it tends to be prohibitively slow. The export feature copies your store as-is, and it's working as intended.

OpenKeychain allows you to export secret keys, so your solution here would be to use that functionality to bring your phone's key to your PC and then make the `.gpg-id` change there so the `pass` CLI can re-encrypt your store.
