### ISSUE TITLE
[FEATURE] Using Colors to Differentiate Character Types

### ISSUE THREAD

**Issue by jtw023** [zeapo/Android-Password-Store#3073]
### Is your feature request related to a problem? Please describe.

Just yesterday I downloaded the android pass app from the google play store since I was told that version is always the latest while the f-droid one is missing certain features.

I was reading #3066 and thought that the way the iOS pass app handles differentiating character types might be a font agnostic way to handle that.

### Describe the solution you'd like

Is this an option to implement?
![session-2024-05-30-105830](https://github.com/android-password-store/Android-Password-Store/assets/59935328/8000f0b3-ed42-491e-b966-7f5856a2c0ed)

### Describe alternatives you've considered

I've looked through the settings on the current version installed from google play and could not find anything like this already implemented.

### Additional context

I have been a long time user of the f-droid pass app on android as well as the iOS pass app. This is my first time trying the google play pass app.

**Comment by msfjarvis** [comment]
FWIW both Google Play and F-Droid have near identical builds of the app ([differences explained here](https://docs.passwordstore.app/docs/users/build-types)), the comment about Google Play being more up-to-date is simply due to us uploading the binaries right away and F-Droid building their own where the queue is always backed up for a week. The _actual_ latest version of the app is always the [snapshot build](https://docs.passwordstore.app/docs/users/release-channels/) which has accumulated a lot of [breaking changes](https://github.com/android-password-store/Android-Password-Store/blob/develop/CHANGELOG.md#unreleased) in the past 3 or so years.

That being said, the font ambiguity problem is mostly dealt with for now so while this looks like a good idea I don't have any motivation to implement it. I've been trying to get back into the swing of bug fixing and there's just so much higher priority stuff to take care of.

**Comment by jtw023** [comment]
@msfjarvis I don't have any time at the moment but perhaps I can take a shot at it one day if help is still needed once I do gain some free time. It would probably be at least a few months since I'm in the process of moving to a new country currently.

How would I go about testing my fork on android? Or is it easier to just run it on my linux laptop?

**Comment by msfjarvis** [comment]
> @msfjarvis I don't have any time at the moment but perhaps I can take a shot at it one day if help is still needed once I do gain some free time. It would probably be at least a few months since I'm in the process of moving to a new country currently.
> 
> How would I go about testing my fork on android? Or is it easier to just run it on my linux laptop?

When you run the app via Android Studio it should install a debug build that has a different package name and will install alongside the build that we distribute without affecting its data.

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
