### ISSUE TITLE
Cannot push to remote repository

### ISSUE THREAD

**Issue by faxal** [zeapo/Android-Password-Store#310]
Whenever I try to push to remote repository I get the following in logs and it does not push new commits.

```
06-18 19:46:53.539   778  2740 I ActivityManager: START u0 {cmp=com.zeapo.pwdstore/.git.GitActivity (has extras)} from uid 10206 on display 0
06-18 19:46:53.542  3981  3981 W Binder_E: type=1400 audit(0.0:1632821): avc: denied { ioctl } for path="socket:[36843265]" dev="sockfs" ino=36843265 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
06-18 19:46:53.542  3981  3981 W Binder_E: type=1400 audit(0.0:1632822): avc: denied { ioctl } for path="socket:[36843265]" dev="sockfs" ino=36843265 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
06-18 19:46:53.602  2461  2461 W Binder_5: type=1400 audit(0.0:1632823): avc: denied { ioctl } for path="socket:[36843405]" dev="sockfs" ino=36843405 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
06-18 19:46:53.602  2461  2461 W Binder_5: type=1400 audit(0.0:1632824): avc: denied { ioctl } for path="socket:[36843405]" dev="sockfs" ino=36843405 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
06-18 19:46:53.642  2729  2729 W Binder_B: type=1400 audit(0.0:1632825): avc: denied { ioctl } for path="socket:[36843265]" dev="sockfs" ino=36843265 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
06-18 19:46:53.642  2729  2729 W Binder_B: type=1400 audit(0.0:1632826): avc: denied { ioctl } for path="socket:[36843265]" dev="sockfs" ino=36843265 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
06-18 19:46:53.671  4950  4950 D REPO    : current path: /data/user/0/com.zeapo.pwdstore/files/store
06-18 19:46:53.673  4950  4950 D PASS    : Check, dir: /data/user/0/com.zeapo.pwdstore/files/store
06-18 19:46:53.673  4950  4950 D PASS    : Check, dir: /data/user/0/com.zeapo.pwdstore/files/store
06-18 19:46:53.662  2740  2740 W Binder_D: type=1400 audit(0.0:1632827): avc: denied { ioctl } for path="socket:[36843265]" dev="sockfs" ino=36843265 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
06-18 19:46:53.662  2740  2740 W Binder_D: type=1400 audit(0.0:1632828): avc: denied { ioctl } for path="socket:[36843265]" dev="sockfs" ino=36843265 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
06-18 19:46:53.733  4950  4950 E WindowManager: 
06-18 19:46:53.733  4950  4950 E WindowManager: android.view.WindowLeaked: Activity com.zeapo.pwdstore.git.GitActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{a63b417 V.E...... R....... 0,0-1026,682} that was originally added here
```

**Comment by zeapo** [comment]
What version?

Le 18 juin 2017 4:49 PM, "fazal" <notifications@github.com> a écrit :

Whenever I try to push to remote repository I get the following in logs and
it does not push new commits.

06-18 19:46:53.539   778  2740 I ActivityManager: START u0
{cmp=com.zeapo.pwdstore/.git.GitActivity (has extras)} from uid 10206
on display 0
06-18 19:46:53.542  3981  3981 W Binder_E: type=1400
audit(0.0:1632821): avc: denied { ioctl } for path="socket:[36843265]"
dev="sockfs" ino=36843265 ioctlcmd=7704 scontext=u:r:system_server:s0
tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
06-18 19:46:53.542  3981  3981 W Binder_E: type=1400
audit(0.0:1632822): avc: denied { ioctl } for path="socket:[36843265]"
dev="sockfs" ino=36843265 ioctlcmd=7704 scontext=u:r:system_server:s0
tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
06-18 19:46:53.602  2461  2461 W Binder_5: type=1400
audit(0.0:1632823): avc: denied { ioctl } for path="socket:[36843405]"
dev="sockfs" ino=36843405 ioctlcmd=7704 scontext=u:r:system_server:s0
tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
06-18 19:46:53.602  2461  2461 W Binder_5: type=1400
audit(0.0:1632824): avc: denied { ioctl } for path="socket:[36843405]"
dev="sockfs" ino=36843405 ioctlcmd=7704 scontext=u:r:system_server:s0
tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
06-18 19:46:53.642  2729  2729 W Binder_B: type=1400
audit(0.0:1632825): avc: denied { ioctl } for path="socket:[36843265]"
dev="sockfs" ino=36843265 ioctlcmd=7704 scontext=u:r:system_server:s0
tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
06-18 19:46:53.642  2729  2729 W Binder_B: type=1400
audit(0.0:1632826): avc: denied { ioctl } for path="socket:[36843265]"
dev="sockfs" ino=36843265 ioctlcmd=7704 scontext=u:r:system_server:s0
tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
06-18 19:46:53.671  4950  4950 D REPO    : current path:
/data/user/0/com.zeapo.pwdstore/files/store
06-18 19:46:53.673  4950  4950 D PASS    : Check, dir:
/data/user/0/com.zeapo.pwdstore/files/store
06-18 19:46:53.673  4950  4950 D PASS    : Check, dir:
/data/user/0/com.zeapo.pwdstore/files/store
06-18 19:46:53.662  2740  2740 W Binder_D: type=1400
audit(0.0:1632827): avc: denied { ioctl } for path="socket:[36843265]"
dev="sockfs" ino=36843265 ioctlcmd=7704 scontext=u:r:system_server:s0
tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
06-18 19:46:53.662  2740  2740 W Binder_D: type=1400
audit(0.0:1632828): avc: denied { ioctl } for path="socket:[36843265]"
dev="sockfs" ino=36843265 ioctlcmd=7704 scontext=u:r:system_server:s0
tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
06-18 19:46:53.733  4950  4950 E WindowManager:
06-18 19:46:53.733  4950  4950 E WindowManager:
android.view.WindowLeaked: Activity com.zeapo.pwdstore.git.GitActivity
has leaked window
com.android.internal.policy.PhoneWindow$DecorView{a63b417 V.E......
R....... 0,0-1026,682} that was originally added here

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zeapo/Android-Password-Store/issues/310>, or mute the
thread

**Comment by faxal** [comment]
Android: 6.0.1
App: 1.2.0.61

**Comment by zeapo** [comment]
you should get an update from F-Droid tomorrow. It seems like F-droid does not support suffixes to versions :s

**Comment by faxal** [comment]
Good to know. Thank you

**Comment by faxal** [comment]
I see the version bump in repo, but F-Droid is still at 61. How long does it take usually?, since I don't know the process.

**Comment by zeapo** [comment]
I don't know :s

really strange, i see the 62 here: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.zeapo.pwdstore.txt

**Comment by faxal** [comment]
I couldn't wait any longer. I've installed from repo directly and it now works. Thanks a lot

**Comment by steveeJ** [comment]
> really strange, i see the 62 here: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.zeapo.pwdstore.txt

The [package in the f-droid repository](https://f-droid.org/repository/browse/?fdid=com.zeapo.pwdstore) has not progressed from 61 yet. Maybe the _-alpha_ is causing trouble.

**Comment by zeapo** [comment]
The 64 that will come soon (hopefully) to f-droid will revert the changes made in 61 that led to this bug.
