### ISSUE TITLE
[BUG] [SECURITY] Passwords are shown in clear-text in the clipboard display

### ISSUE THREAD

**Issue by strk** [zeapo/Android-Password-Store#3129]
### Describe the bug

The password is shown in clear when copied to clipboard

### Steps to reproduce

Open a password record, touch the copy icon, move to another app, focus an input box and see your password in clear in the clipboard display suggestion from android keyboard

### Expected behavior

The password is hidden

### Screenshots

![photo_2024-07-22_09-38-30](https://github.com/user-attachments/assets/90ec9485-1af2-4426-b26c-351d65273436)

### Device information

- Device: Motorola moto g(10) XT2127-2
- OS: Android 11
- App version: 1.13.5

**Comment by msfjarvis** [comment]
This is already fixed in the current development branch, you can upgrade to a snapshot from [here](https://docs.passwordstore.app/docs/users/release-channels/) to get that and [other improvements](https://github.com/android-password-store/Android-Password-Store/blob/develop/CHANGELOG.md#unreleased).

**Comment by strk** [comment]
Last release is from 2021, when is a new release expected ? I'd prefer installing a well-known release

**Comment by strk** [comment]
I would reopen this also because the new code is documented to be possibly incompatible with the old so upgrade is not trival. This ticket would be for a backport of the fix, if possible

**Comment by msfjarvis** [comment]
A backport is not possible because Google Play will not allow the app to publish updates as long as it still requires access to external storage, a feature that too many users rely on for it to be broken silently by an automatic update.

The app has accumulated a lot of breaking changes since the last stable release and needs a lot more work to fill in the gaps left by OpenKeychain's deprecation so a release is not happening in the near future.

**Comment by msfjarvis** [comment]
https://github.com/orgs/android-password-store/projects/1 all the pending issues that need to be addressed for a v2 release are available in the project board, for contributions and tracking progress.
