### ISSUE TITLE
Secruity Bug

### ISSUE THREAD

**Issue by beli3ver** [zeapo/Android-Password-Store#335]
Hi,

I think I find a bug.
When you unlock a key, and then edit the key you can change the name and password ok.
But, when I send the app in the background or take a call or something else, the safe and the password are still unlock.
When I go back to the app I can see the password, copy the password and/or change the password.
I think here must be a protection, that the store is lock when the app is send in the background!

**Comment by zeapo** [comment]
Hi,

That's indeed a bug!

Thanks

On Aug 23, 2017 7:18 PM, "Malte Kiefer" <notifications@github.com> wrote:

Hi,

I think I find a bug.
When you unlock a key, and then edit the key you can change the name and
password ok.
But, when I send the app in the background or take a call or something
else, the safe and the password are still unlock.
When I go back to the app I can see the password, copy the password and/or
change the password.
I think here must be a protection, that the store is lock when the app is
send in the background!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zeapo/Android-Password-Store/issues/335>, or mute the
thread

**Comment by zeapo** [comment]
I'm unable to replicate this on the latest version (69) could you try it please?

**Comment by zeapo** [comment]
Oh, what version of android are you using?
