### ISSUE TITLE
Forget PrivKey Password

### ISSUE THREAD

**Issue by sjau** [zeapo/Android-Password-Store#379]
Hi there

I'm not sure if this should be filed against password store or openkey-chain. So I open password store on my droid and it prompts me the first time to provide the password for the private key. I enter that and then I can access the pass files.

However, it seems the password to the privkey never expires. As long as I don't reboot my cellphone, pass entries will stay unlocked. I would wish that after some time that I can't access the pass files anymore without entering again the gpg privkey password.

**Comment by erayd** [comment]
Pretty sure this would be an OpenKeychain thing. It has a setting for how long to remember passwords (it's a dropdown in the pinentry popup, not in the main settings).

I use a hardware token, so what I'm entering is the token PIN rather than a password for the actual private key - so I can't guarantee that this also applies to key passwords - but it seems likely.

**Comment by sjau** [comment]
Yes it is an OpenKeychain thing. On the dialog where you have to enter your password there's just below the entry a dropdown until when it should keep it in memory. I've seen it quite a few time but never actually conciously noticed it.

Fixed it until screensaver/black screen comes :)
