### ISSUE TITLE
Android-Password-Store is incompatible with OpenKeyChain version 3.2

### ISSUE THREAD

**Issue by pgaubatz** [zeapo/Android-Password-Store#77]
There seem to be (minor?) API changes in OpenKeyChain (i.e., version 3.1 to 3.2) that actually do "break" Android-Password-Store...

**Comment by victorcoder** [comment]
+1

**Comment by zeapo** [comment]
The version 3.2 has been released. I will work on this issue tonight.

**Comment by dschuermann** [comment]
Hey, OpenKeychain developer here.
What exactly breaks Password Store? OK should be backward compatible. There was a small regression which has been fixed in 3.2.1, where encryption was not done automatically to the account key.

With 3.2 we introduced some major API changes, which could be very interesting for Password Store. The API lib and an example can be found on https://github.com/open-keychain/openpgp-api . The API lib is now also available on JCenter (see README in that repo).
It's not perfectly documented right now, but the example should show the new OpenPgpKeyPreference which allows the selection of a private key from the client side, which was previously only possible via the "accounts" (which are now deprecated). For a full version history, look into https://github.com/open-keychain/openpgp-api/blob/master/openpgp-api/src/main/java/org/openintents/openpgp/util/OpenPgpApi.java
Sry for being short on documentation (it's a part time project), if you have more questions don't hesitate to ask here.

**Comment by zeapo** [comment]
Hey @dschuermann ,

Thanks for the comment, the new version is simple to use indeed. I will use the sign key preference in the next version (tested it, and commented the code). The comments on your code are clear enough for the API to be usable :)

The breaking change was the unavailability of `OpenPgpListPreference`.

**Comment by dschuermann** [comment]
@zeapo A great. The preference was simply renamed to OpenPgpAppPreference
