### ISSUE TITLE
[FEATURE] Keyboard (IME) support

### ISSUE THREAD

**Issue by auscompgeek** [zeapo/Android-Password-Store#889]
Some misguided apps don't allow autofill. It'd be great if APS was also an input method to avoid having to use the clipboard.

**Comment by msfjarvis** [comment]
I'm sorry, this is far too much work and complexity for something that I personally would never use.

**Comment by sudomain** [comment]
> avoid having to use the clipboard.

This is the single reason I use KeePassDX over Password Store. The [Android clipboard is not to be trusted with private information](https://github.com/grepx/android-clipboard-security) A password manager that solely relies the clipboard to enter passwords essentially advertises those passwords to any app that wants to listen. Listening apps may not know which service a given password is for, but once this situation occurs the password can be moved over the network and the user is left to rely on security through obscurity. A keyboard input such as KeePassDX's Magikeyboard (or others for closed source apps) is essential for any android password manager. 

I'm not commenting to advertise for KeePassDX: I'd very much like to switch to Password Store and it's git/gpg based system, but a keyboard input is essential for me.

**Comment by fmeum** [comment]
> > avoid having to use the clipboard.
> 
> This is the single reason I use KeePassDX over Password Store. The [Android clipboard is not to be trusted with private information](https://github.com/grepx/android-clipboard-security) A password manager that solely relies the clipboard to enter passwords essentially advertises those passwords to any app that wants to listen. Listening apps may not know which service a given password is for, but once this situation occurs the password can be moved over the network and the user is left to rely on security through obscurity. A keyboard input such as KeePassDX's Magikeyboard (or others for closed source apps) is essential for any android password manager. 
> 
> I'm not commenting to advertise for KeePassDX: I'd very much like to switch to Password Store and it's git/gpg based system, but a keyboard input is essential for me.

Just to get a better understanding of your specific situation: Why is Autofill not resolving this issue for you?

**Comment by sudomain** [comment]
As @auscompgeek said

> Some misguided apps don't allow autofill. 

Nor should it always work: There are a few scenarios in a terminal emulator I use named [Termux](https://termux.com/) where I would not want autofill (ssh key passphrases, gpg, etc.)

**Comment by msfjarvis** [comment]
> As @auscompgeek said
> 
> > Some misguided apps don't allow autofill.

Yes, that's exactly what we want to know: what apps?

> 
> Nor should it always work: There are a few scenarios in a terminal emulator I use named [Termux](https://termux.com/) where I would not want autofill (ssh key passphrases, gpg, etc.)

You still have to manually make a selection before Autofill will write anything into any fields, if that's what your concern is.

**Comment by sudomain** [comment]
> Yes, that's exactly what we want to know: what apps?

Websites in Firefox/Fennec F-Droid are a big one (github, reddit, ...). Is Password Store meant to be used with web browsers?



>     Nor should it always work: There are a few scenarios in a terminal emulator I use named Termux where I would not want autofill (ssh key passphrases, gpg, etc.)

> You still have to manually make a selection before Autofill will write anything into any fields, if that's what your concern is.

My concern here was more along the lines of complex embedded password scenarios: If I'm in Termux and I'm ssh'ed into a different machine, I may or may not want a password to be autofilled from Password Store. Writing a framework into Termux that would allow this would take a lot of work.

Another way to think about it (that's not Termux specific): If I'm connected to a VNC server via MultiVNC or another VNC client app, I may need to supply passwords in my password manager  through the VNC client. Currently my options with Password Store are:
1. Risk using the clipboard
2. Manually type a long password that consists of pseudorandom characters while switching many times between my VNC client and Password Store
3. Request that my VNC client implement some mechanism to take the Android autofill and pass it through to the application running on the VNC server.

1 is unrealistic from a security perspective. 2 is something I'll rarely be willing to do considering other password manager apps can take my long pseudorandom password and pass it through their dedicated keyboard input. 3 is a possibility, but the devs of a VNC client might say "why not just switch to a password manager that can enter passwords via keyboard input such as KeePassDX or (closed source) LastPass.

**Comment by fmeum** [comment]
@sudomain Thanks for the elaboration, I think that I now have a much better picture of your threat model and use cases. I will think about what we can do.

Just one more question: When I developed password store's Autofill functionality, I found Firefox's Autofill support to be rather good. Does it not work for you in the case of e.g. reddit?

**Comment by sudomain** [comment]
>  I will think about what we can do.

Thank you for considering it.

> I found Firefox's Autofill support to be rather good. Does it not work for you in the case of e.g. reddit?

For me it does not. Might have something to do with matching the URL? (I use old.reddit.com). Additionally I have browser extensions that could be affecting autofill: NoScript, HTTPSEverywhere, uBlock origin

**Comment by fmeum** [comment]
> > I found Firefox's Autofill support to be rather good. Does it not work for you in the case of e.g. reddit?
> 
> For me it does not. Might have something to do with matching the URL? (I use old.reddit.com). Additionally I have browser extensions that could be affecting autofill: NoScript, HTTPSEverywhere, uBlock origin

This is weird, I just confirmed that it works very well for me on old.reddit.com in Firefox (with only ublock origin). It looks as follows:

![Screenshot_20200720-222441.png](https://user-images.githubusercontent.com/4312191/87984589-7900d380-cada-11ea-8331-47528257b280.png)

Do you get similar Autofill prompts in other apps?

**Comment by sudomain** [comment]
> Do you get similar Autofill prompts in other apps?

For other apps I get prompts like the following:

![Screenshot_2020-07-20-17-48-48](https://user-images.githubusercontent.com/30786326/87990137-6625d900-cab1-11ea-802a-a1aa171f666d.png)

**Comment by fmeum** [comment]
> > Do you get similar Autofill prompts in other apps?
> 
> For other apps I get prompts like the following:
> 
> ![Screenshot_2020-07-20-17-48-48](https://user-images.githubusercontent.com/30786326/87990137-6625d900-cab1-11ea-802a-a1aa171f666d.png)
> 

Your screenshot shows the legacy accessibility implementation of Autofill. Which versions of Android and Password Store are you using?

**Comment by sudomain** [comment]
Android 7.0, Password Store 1.9.2 from Fdroid

**Comment by msfjarvis** [comment]
Ah Android 7, bummer. Android only had real Autofill support from 8.0 so all our improvements are only made in that variant of the Autofill service.

**Comment by fmeum** [comment]
I have read up on Android clipboard access now. The situation has changed since the repository you linked to was last updated (around three years ago). As of Android Q (i.e. Android 10, API level 29), [a third-party app can only access the clipboard if it either has focus or provides the currently used IME, regardless of its targeted API level](https://cs.android.com/android/platform/superproject/+/android10-release:frameworks/base/services/core/java/com/android/server/clipboard/ClipboardService.java;l=741;drc=56904d05878fe8698cb3336fdfd954c23878d24d), which should fully address your concerns. That means that while the Android clipboard cannot be trusted to keep password private in Android P and below, it is a secure channel on Android Q and up.

The legacy Autofill implementation you are currently using is in fact quite limited and prone to breakage. It is not easy to do better given that its backend is solely inteded to provide accessibility services to users and credential Autofill is only something that password managers can try to hack into it. The support in browsers is generally not good. As of Android Oreo, a proper Autofill API has been available which e.g. works very well with Firefox Preview. In Android Pie, a compatibility mode was added that also offers quite reliable Autofill in apps that don't support it directly such as Firefox, Fennec and Chromium derivates. While Termux and MultiVNC do not support Autofill yet, it would be very easy and generally useful to add an Autofill context menu action to them. I would happily discuss that with the maintainers.

In summary, I believe that the current version of Password Store on a phone with Android Q or higher already offers almost everything you are asking for: a convenient, secure Autofill mechanism for websites and most apps as well as a somewhat inconvenient, but secure fallback in the form of clipboard copy & paste (note that Password Store also offers a notification with which you can clear the clipboard and does so automatically after a timeout, in case you are worried of foreground apps snooping on it later).

@sudomain I'm hesitant to consider adding a solution that is specific to older Android versions, in particular to Android 7 and lower. Android 7 currently has [247 vulnerabilities with a CVE and a CVSS score of 9 and higher](https://www.cvedetails.com/vulnerability-list.php?vendor_id=1224&product_id=19997&version_id=201744&page=3&hasexp=0&opdos=0&opec=0&opov=0&opcsrf=0&opgpriv=0&opsqli=0&opxss=0&opdirt=0&opmemc=0&ophttprs=0&opbyp=0&opfileinc=0&opginf=0&cvssscoremin=9&cvssscoremax=0&year=0&month=0&cweid=0&order=3&trc=247&sha=0e2d360f1e14be3ac391ebfe0fe9563a7bcf53e2), many of which are local privilege escalation vulnerabilities that do not require any user interaction (or worse). While snooping on the clipboard via official Android APIs is certainly much easier than exploiting any of these, any app on your phone is potentially in a position to completely control your phone without any indication of compromise. Adding any kind of "secure password typing" functionality to an app running on Android 7 would thus only provide a dangerously false sense of security.

If you care deeply about the security of your VNC sessions and passwords in general, as I can see you do, I would strongly recommend you to update to a recent version of Android, maybe relying on a popular and trusted custom ROM if official updates should no longer be available. If that shouldn't be possible, you should at least ensure that you only install and run trusted apps. 

As you can probably tell, I do tend to have strong opinions in security matters of this kind. @msfjarvis and I are still open to feedback and ideas though, so please let us you know if your point of view should differ from mine.

**Comment by fmeum** [comment]
Since it was quick and easy, I added Autofill support to Termux: https://github.com/termux/termux-app/pull/1664

**Comment by msfjarvis** [comment]
The Termux PR has been merged, so there's nothing left to do here. Closing.
