### ISSUE TITLE
Optionaly use gpg secret key on remote server insted of locally stored

### ISSUE THREAD

**Issue by TiiXel** [zeapo/Android-Password-Store#92]
Currently, Android-Password-Store requires both encrypted passwords and gpg keys to be stored on the smartphone. Of course, this is very convenient as it does not require an internet connexion to decrypt passwords.

But I think this is a kind of security issue as, would my smartphone be stolen, the only wall between hacker and passwords is the passphrase.

Android-Password-Store uses ssh to log in remote server and sync git repository. I think it could use this ssh connexion to decrypt passwords with remote gpg key. This is my idea :

* Passwords are stored on smartphone, encrypted with gpg public key
* Android-Password-Store know ssh secret key to log in remote ssh server
* Remote ssh server know gpg secret key to decrypt passwords
* Remote ssh server allows Android-Password-Store to log in

When user asks for a passwords, the following happens :

* Password-Store search for asked encrypted passwords file
* Password-Store connects to remote ssh server
* Through ssh : Password-Store sends encrypted file, then runs `gpg --decrypt`for this file
* Password-Store reads the output wich is the plain text password asked by user

This way, if smartphone is stolen, the only thing to do is to remove the smartphone's rsa public key for ssh connexion into the server. Then passwords are left encrypted on the smartphone with no way to decrypt them.

The problem now is that a trusted ssh server is required to store the gpg secret key. But, on this server, there is no need to store the encrypted passwords. So the security is not compromised as there is no place where both data and secret key are stored.

I'm not sure my suggestion is easy to program... It may be simple in principle, but harder to implement.

**Comment by zeapo** [comment]
This can be a good idea for people who, indeed, trust only their server rather than their device.

For this to work, we'll have to execute remote command such as `pass my/pass/word` [using ssh](http://www.cyberciti.biz/faq/unix-linux-execute-command-using-ssh/).

I don't know how to do it yet, nor if it is easy to do :)

**Comment by phryneas** [comment]
While this is a way to do it, you might consider using a hardware-token like a yubikey with NFC (works great with OpenKeychain) instead of exposing your gpg key to the internet.

Of course it is theoretically possible to forcibly extract a key from such a hardware token too, but I don't know of such an attack. And the GPG smartcard plugin is set to lock after 3 failes passphrases, which should make brute-forcing even a simple pin near impossible.

**Comment by TiiXel** [comment]
Yeah I have read about yubikey and I think they are a good solution too !

I think my suggestion is no less secure than the yubikey, provided you host and own your server (Raspberry Pi ?). Indeed the yubikey is perfectly safe, secured by the pin. The ssh connexion would be secured by rsa. An attempt to brute force it would be as ineffective as brute forcing the gpg key, wouldn't it ?
Let's say the rsa key for ssh is secured by a passphrase, it would provide time to remove the public one from the authorized keys !

I may be wrong. I'm new to gpg and pass an encryption in general !

Also, sure, this is only an alternative which may not be perfect and which some may not like. Myself, I wouldn't like the smaetcard simply because, where my smartphone would be

**Comment by phryneas** [comment]
I was more thinking about things like shellshock or heartbleed (or, if you're running wordpress or something alike on the server: CVE-1900-1 to CVE-2030-n+1 ;) ): if you are running more than just ssh and gpg on your server, there are other channels it can be compromised.

Yes, it would need a highly targeted attack - but at the same time someone stealing your phone would probably wipe & sell it, not try to bruteforce the GPG key on it - so we're talking about similar level of "targeted" attack there, too.

Your idea is an absolutely valid one, and I'm sure some people will find use for it, but depending on how seriously you take key security it could actually lower it (especially if you are gpg-agent on the server) rather than strengthen it as you are switching from one or two possible attackers (that physically obtained the phone)  to a scenario with thousands of potential attackers (the internet).

**Comment by TiiXel** [comment]
Well, you're right about it all. Especially the wipe and sell thing, for
sure. I didn't think about heardbleed & Co., but it is indeed a real issue.

"Don't keep personal data online" is wise advice and my suggestion goes
against it, I understand.
On the other hand "Don't write down your passwords and post-it onto your
screen" is recommended too and, to me, having the key and encrypted
passwords on the same device is this.
Still, it's probably safer to have passwords handwritten on the desk rather
than the same password everywhere – provided you trust people you live
with. Likelihood to be the target of a burglary is no higher than to be
hacked, depending on a few factors.

If I had to sum up everything in one sentence I'd said that, whatever you
do, you can't hope for 100% security. And you can hardly get close to it.
Even your gpg key should be backed up on paper, they say.
