### ISSUE TITLE
[BUG] OTP entries aren't being treated as OTP passwords

### ISSUE THREAD

**Issue by craigcabrey** [zeapo/Android-Password-Store#967]
**Describe the bug**
1.10.0 added back OTP (TOTP) entries. I have existing OTP entries (just moved over from iOS where they were working fine with mssun/passforios) but when I look at the entry in APS, I just see `Password: otpauth://totp/[...]`.

**To Reproduce**
1. Open an OTP entry
2. See the standard password view instead of an OTP code

**Expected behavior**

**Device information (please complete the following information):**
 - Device: Samsung Galaxy S20
 - OS: Stock ROM, Android 10
 - App version 1.10.0

**Additional context**
Does the entry need to be labeled specially? I saw in the code it just looks for [`startsWith("otpauth://totp/")`](https://github.com/android-password-store/Android-Password-Store/blob/c5a93b8b8168eead37f3f93a8e8378211c1d240b/app/src/main/java/com/zeapo/pwdstore/utils/UriTotpFinder.kt#L17) so I don't think there is anything else I need to do.

**Comment by msfjarvis** [comment]
This is awkward. Is the TOTP URL the first line of your password file's content?

**Comment by craigcabrey** [comment]
> This is awkward. Is the TOTP URL the first line of your password file's content?

Yea:

```
$ pass social/craigcabrey@github
otpauth://totp/GitHub:craigcabrey?secret=[...]&issuer=GitHub
```

**Comment by msfjarvis** [comment]
> > This is awkward. Is the TOTP URL the first line of your password file's content?
> 
> Yea:
> 
> ```
> $ pass social/craigcabrey@github
> otpauth://totp/GitHub:craigcabrey?secret=[...]&issuer=GitHub
> ```

That'd probably explain it. What happens here is that the app always selects the first line as the password, and everything that follows it as [extra content](https://github.com/android-password-store/Android-Password-Store/blob/e3cf73885c112bc553d6a0cc01d594a87728f448/app/src/main/java/com/zeapo/pwdstore/model/PasswordEntry.kt#L89). In your case, because there is only one line, there is no extra content, just the password. That's why no OTP is generated, and it's also why you see your TOTP URI in the password field. I'll see what can be done. Thanks for the report!

**Comment by msfjarvis** [comment]
I've pushed out a fix for this that works on my end. I've marked it as a backport candidate for when we next decide to do an incremental patch release, in the mean time you can get the fixed version from the snapshot builds directory linked in the README once the PR is merged.

**Comment by craigcabrey** [comment]
thanks for the fix, contributed to the project's beer fund :beers:
